(() => {
  const URL='https://zycpeiyztqysjqejtour.supabase.co';
  const KEY='sb_publishable_heHXvAxo36EvgHg_8_XOXQ_rRxE5t5H';
  const sb=window.supabase?.createClient(URL,KEY);if(!sb)return;
  const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  let source='rumo';
  function toast(msg){let el=qs('.rumo-toast');if(!el){el=document.createElement('div');el.className='rumo-toast';document.body.appendChild(el)}el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
  function inject(){
    const head=qs('.focus-card .card-heading');if(head&&!qs('#log-study-btn')){const actions=document.createElement('div');actions.className='focus-actions';const progress=head.querySelector('.progress');if(progress)actions.appendChild(progress);const btn=document.createElement('button');btn.id='log-study-btn';btn.className='log-study-btn';btn.textContent='+ Registrar estudo';actions.appendChild(btn);head.appendChild(actions);btn.onclick=()=>qs('#study-log-modal').classList.add('open')}
    if(!qs('#study-log-modal'))document.body.insertAdjacentHTML('beforeend',`<div id="study-log-modal" class="modal"><div class="modal-card study-log-shell"><button class="close" id="close-study-log">×</button><div class="eyebrow">REGISTRO DE ESTUDO</div><h2>O que você estudou?</h2><p>Vale estudo feito dentro ou fora do RUMO. YouTube, PDF, livro e outro curso também contam para seu progresso.</p><form id="study-log-form" class="form-grid"><div class="field"><label>Matéria</label><input id="log-subject" required placeholder="Ex.: Português"></div><div class="field"><label>Assunto</label><input id="log-topic" placeholder="Ex.: Interpretação de texto"></div><div class="field"><label>Onde estudou?</label><div class="study-source-grid"><button type="button" class="study-source selected" data-source="rumo">RUMO</button><button type="button" class="study-source" data-source="youtube">YouTube</button><button type="button" class="study-source" data-source="pdf">PDF / Livro</button><button type="button" class="study-source" data-source="externo">Curso externo</button></div></div><div class="field"><label>Tempo estudado (min)</label><input id="log-minutes" type="number" min="1" max="1440" value="30" required></div><div class="question-row"><div class="field"><label>Questões feitas</label><input id="log-questions" type="number" min="0" value="0"></div><div class="field"><label>Acertos</label><input id="log-correct" type="number" min="0" value="0"></div></div><div id="log-message" class="form-message"></div><button class="primary" type="submit">Salvar no meu progresso</button></form></div></div>`);
    qs('#close-study-log').onclick=()=>qs('#study-log-modal').classList.remove('open');qs('#study-log-modal').onclick=e=>{if(e.target.id==='study-log-modal')e.target.classList.remove('open')};qsa('.study-source').forEach(b=>b.onclick=()=>{qsa('.study-source').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');source=b.dataset.source});qs('#study-log-form').onsubmit=save;
  }
  async function save(e){e.preventDefault();const msg=qs('#log-message');msg.textContent='Salvando...';const {data:{session}}=await sb.auth.getSession();if(!session?.user){msg.className='form-message error';msg.textContent='Entre na sua conta para salvar estudos entre dispositivos.';return}const questions=Math.max(0,+qs('#log-questions').value||0);const correct=Math.max(0,Math.min(questions,+qs('#log-correct').value||0));const {data:goal}=await sb.from('user_goals').select('id').eq('user_id',session.user.id).eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();const {error}=await sb.from('study_sessions').insert({user_id:session.user.id,goal_id:goal?.id||null,subject:qs('#log-subject').value.trim(),topic:qs('#log-topic').value.trim()||null,minutes:+qs('#log-minutes').value,questions,correct_answers:correct,source});if(error){msg.className='form-message error';msg.textContent='Não consegui salvar agora.';return}msg.className='form-message success';msg.textContent='Estudo salvo.';setTimeout(()=>qs('#study-log-modal').classList.remove('open'),300);setTimeout(()=>qs('#account-sync')?.click(),350);toast('Sessão adicionada ao seu progresso')}
  setTimeout(inject,1100);
})();
