(() => {
  'use strict';
  const R=()=>window.RUMO;
  let step=1,draft={study_days:[1,2,3,4,5],level:'iniciante',weekly_hours:10};
  const initials=(v='R')=>v.trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||'R';

  function markup(){
    if(document.querySelector('#auth-v3'))return;
    const top=R().qs('.top-actions');
    if(top&&!R().qs('#account-btn')){const b=document.createElement('button');b.id='account-btn';b.className='account-btn';b.innerHTML='<span class="account-dot"></span><span id="account-label">Entrar</span>';top.insertBefore(b,R().qs('.user'))}
    const strip=R().qs('.objective-strip');
    if(strip&&!R().qs('#personalize-btn')){const b=document.createElement('button');b.id='personalize-btn';b.className='personalize-btn';b.textContent='Personalizar meu RUMO';strip.appendChild(b)}
    document.body.insertAdjacentHTML('beforeend',`
      <div id="auth-v3" class="modal"><div class="modal-card auth-shell"><button class="close" data-close-v3="auth-v3">×</button><div class="auth-brand"><div class="auth-brand-mark">R</div><div><strong>RUMO</strong><span>Seu progresso, em qualquer dispositivo.</span></div></div><h2>Entre no seu RUMO</h2><p>Crie uma conta grátis para salvar objetivo, rotina e evolução.</p><div class="auth-tabs"><button class="auth-tab active" data-auth-v3="login">Entrar</button><button class="auth-tab" data-auth-v3="signup">Criar conta</button></div><form id="auth-form-v3" class="form-grid"><div class="field signup-v3" hidden><label>Seu nome</label><input id="auth-name-v3" autocomplete="name" placeholder="Como quer ser chamado?"></div><div class="field"><label>E-mail</label><input id="auth-email-v3" type="email" autocomplete="email" required placeholder="voce@email.com"></div><div class="field"><label>Senha</label><input id="auth-password-v3" type="password" autocomplete="current-password" required minlength="6" placeholder="Mínimo de 6 caracteres"></div><button type="button" id="forgot-v3" class="text-link" style="justify-self:start">Esqueci minha senha</button><div id="auth-message-v3" class="form-message"></div><button class="primary auth-submit" type="submit">Entrar</button></form></div></div>
      <div id="onboarding-v3" class="modal"><div class="modal-card onboarding-shell"><button class="close" data-close-v3="onboarding-v3">×</button><div class="eyebrow">CONFIGURAÇÃO INICIAL</div><h2>Monte seu RUMO em menos de 1 minuto.</h2><div class="onboarding-progress"><i class="active"></i><i></i><i></i></div><div class="onboarding-step active" data-step-v3="1"><h3>Qual é o seu objetivo?</h3><p>Escolha um concurso do radar ou escreva seu objetivo.</p><div class="form-grid"><div class="field"><label>Concurso / objetivo</label><input id="goal-objective-v3" list="goal-options-v3" placeholder="Ex.: SEFAZ DF 2026"><datalist id="goal-options-v3"></datalist></div><div class="field"><label>Cargo ou foco</label><input id="goal-role-v3" placeholder="Ex.: Auditor, Técnico, ENEM..."></div><div class="field"><label>Data da prova</label><input id="goal-date-v3" type="date"></div></div></div><div class="onboarding-step" data-step-v3="2"><h3>Quanto tempo cabe na sua vida?</h3><p>O plano deve respeitar sua rotina, não competir com ela.</p><div class="form-grid two"><div class="field"><label>Horas por semana</label><input id="goal-hours-v3" type="number" min="1" max="80" step="0.5" value="10"></div><div class="field"><label>Seu nível atual</label><select id="goal-level-v3"><option value="iniciante">Estou começando</option><option value="intermediario">Já tenho uma base</option><option value="avancado">Já estudo há bastante tempo</option></select></div></div><div class="field" style="margin-top:16px"><label>Dias disponíveis</label><div class="days-grid">${[['D',0],['S',1],['T',2],['Q',3],['Q',4],['S',5],['S',6]].map(([d,n])=>`<button type="button" class="day-chip ${draft.study_days.includes(n)?'selected':''}" data-day-v3="${n}">${d}</button>`).join('')}</div></div></div><div class="onboarding-step" data-step-v3="3"><h3>Pronto. O resto é com o RUMO.</h3><p>Seu plano será montado a partir do objetivo, rotina e desempenho real.</p><div class="choice-grid"><button type="button" class="choice selected"><b>Plano adaptativo</b><span>Conteúdo, questões e revisão conforme seu ritmo.</span></button></div></div><div class="onboarding-actions"><button type="button" class="soft-btn" id="back-v3">Voltar</button><div class="right"><button type="button" class="soft-btn" data-close-v3="onboarding-v3">Agora não</button><button type="button" class="primary" id="next-v3">Continuar</button></div></div></div></div>
      <div id="account-v3" class="modal"><div class="modal-card account-shell"><button class="close" data-close-v3="account-v3">×</button><div class="eyebrow">MINHA CONTA</div><h2>Seu espaço no RUMO</h2><div class="account-summary"><div class="account-avatar" id="account-avatar-v3">R</div><div><b id="account-name-v3">Usuário</b><span id="account-email-v3"></span></div></div><div class="account-actions"><button id="account-config-v3">⚙ Ajustar objetivo e rotina</button><button id="account-sync-v3">↻ Atualizar meus dados</button><button id="account-logout-v3" class="danger">Sair da conta</button></div></div></div>`);
    bind();
  }

  function bind(){const r=R();r.qsa('[data-close-v3]').forEach(b=>b.onclick=()=>r.qs('#'+b.dataset.closeV3)?.classList.remove('open'));r.qsa('#auth-v3,#onboarding-v3,#account-v3').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});r.qs('#account-btn').onclick=()=>r.state.user?openAccount():r.qs('#auth-v3').classList.add('open');r.qs('.user').onclick=()=>r.state.user&&openAccount();r.qs('#personalize-btn').onclick=()=>openOnboarding(r.state.goal);r.qsa('[data-auth-v3]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.authV3));r.qs('#auth-form-v3').onsubmit=auth;r.qsa('[data-day-v3]').forEach(b=>b.onclick=()=>{b.classList.toggle('selected');draft.study_days=r.qsa('[data-day-v3].selected').map(x=>+x.dataset.dayV3)});r.qs('#back-v3').onclick=()=>showStep(Math.max(1,step-1));r.qs('#next-v3').onclick=next;r.qs('#forgot-v3').onclick=forgot;r.qs('#account-config-v3').onclick=()=>{r.qs('#account-v3').classList.remove('open');openOnboarding(r.state.goal)};r.qs('#account-sync-v3').onclick=async()=>{await r.sync(true);r.toast('Dados atualizados')};r.qs('#account-logout-v3').onclick=async()=>{await r.sb.auth.signOut();r.qs('#account-v3').classList.remove('open')}}
  function setAuthMode(mode){const r=R();r.qsa('[data-auth-v3]').forEach(x=>x.classList.toggle('active',x.dataset.authV3===mode));r.qsa('.signup-v3').forEach(x=>x.hidden=mode!=='signup');r.qs('#auth-form-v3').dataset.mode=mode;r.qs('#auth-form-v3 .auth-submit').textContent=mode==='signup'?'Criar conta grátis':'Entrar';r.qs('#auth-message-v3').textContent=''}
  async function auth(e){e.preventDefault();const r=R(),mode=e.currentTarget.dataset.mode||'login',email=r.qs('#auth-email-v3').value.trim(),password=r.qs('#auth-password-v3').value,name=r.qs('#auth-name-v3').value.trim(),msg=r.qs('#auth-message-v3');msg.textContent='Aguarde...';const result=mode==='signup'?await r.sb.auth.signUp({email,password,options:{data:{display_name:name||email.split('@')[0]}}}):await r.sb.auth.signInWithPassword({email,password});if(result.error){msg.textContent=/invalid login/i.test(result.error.message)?'E-mail ou senha incorretos.':result.error.message;return}if(mode==='signup'&&!result.data.session){msg.textContent='Conta criada. Confira seu e-mail para confirmar.';return}msg.textContent='Pronto!';setTimeout(()=>r.qs('#auth-v3').classList.remove('open'),180)}
  async function forgot(){const r=R(),email=r.qs('#auth-email-v3').value.trim();if(!email){r.toast('Digite seu e-mail primeiro.');return}const {error}=await r.sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin});r.toast(error?'Não consegui enviar agora.':'Link de recuperação enviado.')}
  function updateAccount(){const r=R(),u=r.state.user,btn=r.qs('#account-label'),avatar=r.qs('.user');if(!btn||!avatar)return;if(u){const name=u.user_metadata?.display_name||u.email?.split('@')[0]||'Usuário';btn.textContent=name.split(' ')[0];avatar.textContent=initials(name);avatar.classList.add('is-live');avatar.classList.remove('is-hidden')}else{btn.textContent='Entrar';avatar.textContent='R';avatar.classList.remove('is-live');avatar.classList.add('is-hidden')}}
  function openAccount(){const r=R(),u=r.state.user;if(!u)return;const name=u.user_metadata?.display_name||u.email?.split('@')[0]||'Usuário';r.qs('#account-name-v3').textContent=name;r.qs('#account-email-v3').textContent=u.email||'';r.qs('#account-avatar-v3').textContent=initials(name);r.qs('#account-v3').classList.add('open')}
  async function openOnboarding(goal=null){const r=R();step=1;draft={study_days:goal?.study_days||[1,2,3,4,5],level:goal?.level||'iniciante',weekly_hours:goal?.weekly_hours||10};r.qs('#goal-objective-v3').value=goal?.objective_name||'';r.qs('#goal-role-v3').value=goal?.cargo||'';r.qs('#goal-date-v3').value=goal?.prova_data||'';r.qs('#goal-hours-v3').value=goal?.weekly_hours||10;r.qs('#goal-level-v3').value=goal?.level||'iniciante';r.qsa('[data-day-v3]').forEach(x=>x.classList.toggle('selected',draft.study_days.includes(+x.dataset.dayV3)));showStep(1);r.qs('#onboarding-v3').classList.add('open');const {data}=await r.sb.from('concursos').select('nome,orgao').order('destaque',{ascending:false}).limit(30);if(data)r.qs('#goal-options-v3').innerHTML=data.map(x=>`<option value="${r.escapeHTML(x.nome)}">${r.escapeHTML(x.orgao)}</option>`).join('')}
  function showStep(n){const r=R();step=n;r.qsa('[data-step-v3]').forEach(x=>x.classList.toggle('active',+x.dataset.stepV3===n));r.qsa('#onboarding-v3 .onboarding-progress i').forEach((x,i)=>x.classList.toggle('active',i<n));r.qs('#back-v3').style.visibility=n===1?'hidden':'visible';r.qs('#next-v3').textContent=n===3?'Criar meu RUMO':'Continuar'}
  async function next(){const r=R();if(step===1){draft.objective_name=r.qs('#goal-objective-v3').value.trim();if(!draft.objective_name){r.toast('Digite seu concurso ou objetivo');return}draft.cargo=r.qs('#goal-role-v3').value.trim()||null;draft.prova_data=r.qs('#goal-date-v3').value||null;showStep(2);return}if(step===2){draft.weekly_hours=Math.max(1,Math.min(80,+r.qs('#goal-hours-v3').value||10));draft.level=r.qs('#goal-level-v3').value;draft.study_days=r.qsa('[data-day-v3].selected').map(x=>+x.dataset.dayV3);if(!draft.study_days.length){r.toast('Escolha pelo menos um dia');return}showStep(3);return}if(!r.state.user){localStorage.setItem('rumo-guest-goal',JSON.stringify({...draft,id:'guest',active:true}));r.qs('#onboarding-v3').classList.remove('open');await r.sync(true);r.toast('Seu RUMO foi criado');return}await r.sb.from('user_goals').update({active:false}).eq('user_id',r.state.user.id).eq('active',true);const {error}=await r.sb.from('user_goals').insert({user_id:r.state.user.id,objective_name:draft.objective_name,cargo:draft.cargo,prova_data:draft.prova_data,weekly_hours:draft.weekly_hours,study_days:draft.study_days,level:draft.level,active:true});if(error){r.toast('Não consegui salvar. Tente novamente.');return}r.qs('#onboarding-v3').classList.remove('open');await r.sync(true);r.toast('Seu RUMO foi atualizado')}

  markup();setAuthMode('login');document.addEventListener('rumo:context',()=>{updateAccount();const r=R();if(r.state.ready&&r.state.user&&!r.state.goal&&!sessionStorage.getItem('rumo-onboarding-shown')){sessionStorage.setItem('rumo-onboarding-shown','1');setTimeout(()=>openOnboarding(),250)}});updateAccount();
})();