(() => {
  'use strict';
  const R=()=>window.RUMO;
  let enabled=true,ready=false,queue=[],flushing=false,lastPage='',prefUser=null;
  const SAFE_EVENTS=new Set(['app_opened','tab_viewed','goal_created','goal_updated','study_session_started','study_session_completed','review_opened','contest_viewed','contest_followed','course_opened','course_lesson_completed','assistant_opened','assistant_message_sent','account_data_exported','legal_consent_recorded','integration_opened','calendar_exported','checkout_started','checkout_unavailable','runtime_error']);
  const cleanMeta=(meta={})=>{const out={};for(const [k,v] of Object.entries(meta||{})){if(!/^[a-z0-9_]{1,40}$/i.test(k))continue;if(typeof v==='string')out[k]=v.slice(0,120);else if(typeof v==='number'||typeof v==='boolean'||v===null)out[k]=v}return out};
  async function loadPreference(force=false){const r=R(),u=r?.state?.user;if(!u){ready=true;enabled=false;prefUser=null;paintToggle();return}if(!force&&prefUser===u.id&&ready)return;const {data,error}=await r.sb.from('user_preferences').select('analytics_enabled').eq('user_id',u.id).maybeSingle();if(!error&&data)enabled=data.analytics_enabled!==false;else enabled=true;prefUser=u.id;ready=true;paintToggle();flush()}
  async function setEnabled(value){enabled=!!value;ready=true;const r=R(),u=r?.state?.user;if(u){prefUser=u.id;await r.sb.from('user_preferences').upsert({user_id:u.id,analytics_enabled:enabled,updated_at:new Date().toISOString()},{onConflict:'user_id'})}if(!enabled)queue=[];paintToggle();return enabled}
  function track(name,meta={}){if(!SAFE_EVENTS.has(name)||!enabled&&ready)return;const r=R(),u=r?.state?.user;if(!u)return;const evt={user_id:u.id,event_name:name,page:document.querySelector('.page.active')?.id||null,metadata:cleanMeta(meta)};queue.push(evt);if(queue.length>30)queue=queue.slice(-30);if(ready)flush()}
  async function flush(){if(flushing||!ready||!enabled||!queue.length)return;const r=R(),u=r?.state?.user;if(!u)return;flushing=true;const batch=queue.splice(0,12);try{const {error}=await r.sb.from('product_events').insert(batch);if(error)console.warn('RUMO analytics degraded',error.message)}catch(_){/* analytics never blocks product */}finally{flushing=false;if(queue.length)setTimeout(flush,800)}}
  function injectToggle(){const r=R(),grid=r?.qs?.('#privacy-v1 .privacy-grid-v1');if(!grid||r.qs('#privacy-analytics-v1'))return;const section=document.createElement('section');section.className='privacy-section-v1';section.id='privacy-analytics-v1';section.innerHTML='<h3>Métricas de uso</h3><p>Ajude a melhorar o RUMO enviando eventos técnicos de uso. Não registramos texto do chat, conteúdo do edital ou respostas digitadas.</p><label class="legal-consent-v1"><input id="privacy-analytics-check-v1" type="checkbox"><span>Permitir métricas de produto não essenciais</span></label><div class="privacy-msg-v1" id="privacy-analytics-msg-v1"></div>';const exportSection=[...grid.children].find(x=>x.querySelector?.('#privacy-export-v1'));grid.insertBefore(section,exportSection||grid.lastElementChild);const check=r.qs('#privacy-analytics-check-v1');check.checked=enabled;check.onchange=async()=>{const msg=r.qs('#privacy-analytics-msg-v1');msg.textContent='Salvando...';await setEnabled(check.checked);msg.textContent=check.checked?'Métricas ativadas.':'Métricas não essenciais desativadas.'}}
  function paintToggle(){const r=R(),check=r?.qs?.('#privacy-analytics-check-v1');if(check)check.checked=enabled}
  function bind(){document.addEventListener('rumo:tab',e=>{const id=e.detail?.id||document.querySelector('.page.active')?.id||'';if(id&&id!==lastPage){lastPage=id;track('tab_viewed',{tab:id})}});document.addEventListener('click',e=>{if(e.target.closest?.('#open-ai,[data-tab="ia"]'))track('assistant_opened');if(e.target.closest?.('#account-integrations-v1'))track('integration_opened');if(e.target.closest?.('.contest-more'))track('contest_viewed');if(e.target.closest?.('#course-grid [data-course]'))track('course_opened');if(e.target.closest?.('#account-privacy-v1'))setTimeout(()=>{injectToggle();paintToggle()},0)},true);window.addEventListener('error',e=>track('runtime_error',{kind:'error',file:String(e.filename||'').split('/').pop()||''}));window.addEventListener('unhandledrejection',()=>track('runtime_error',{kind:'promise'}));window.addEventListener('pagehide',flush)}
  document.addEventListener('rumo:context',()=>{const u=R()?.state?.user;if(!u){ready=true;enabled=false;prefUser=null;paintToggle();return}loadPreference();setTimeout(injectToggle,0)});
  bind();setTimeout(()=>{injectToggle();if(R()?.state?.user)loadPreference();track('app_opened')},1600);
  window.RUMO_ANALYTICS={track,setEnabled,get enabled(){return enabled}};
})();
