(() => {
  'use strict';
  const R=()=>window.RUMO;
  let enabled=true,ready=false,queue=[],flushing=false,lastPage='';
  const SAFE_EVENTS=new Set(['app_opened','tab_viewed','goal_created','goal_updated','study_session_started','study_session_completed','review_opened','contest_viewed','contest_followed','course_opened','course_lesson_completed','assistant_opened','assistant_message_sent','account_data_exported','legal_consent_recorded','integration_opened','calendar_exported','checkout_started','checkout_unavailable','runtime_error']);
  const cleanMeta=(meta={})=>{const out={};for(const [k,v] of Object.entries(meta||{})){if(!/^[a-z0-9_]{1,40}$/i.test(k))continue;if(typeof v==='string')out[k]=v.slice(0,120);else if(typeof v==='number'||typeof v==='boolean'||v===null)out[k]=v}return out};
  async function loadPreference(){const r=R(),u=r?.state?.user;if(!u){ready=true;enabled=false;return}const {data,error}=await r.sb.from('user_preferences').select('analytics_enabled').eq('user_id',u.id).maybeSingle();if(!error&&data)enabled=data.analytics_enabled!==false;else enabled=true;ready=true;flush()}
  async function setEnabled(value){enabled=!!value;const r=R(),u=r?.state?.user;if(u)await r.sb.from('user_preferences').upsert({user_id:u.id,analytics_enabled:enabled,updated_at:new Date().toISOString()},{onConflict:'user_id'});if(!enabled)queue=[];return enabled}
  function track(name,meta={}){if(!SAFE_EVENTS.has(name))return;const r=R(),u=r?.state?.user;if(!u)return;const evt={user_id:u.id,event_name:name,page:document.querySelector('.page.active')?.id||null,metadata:cleanMeta(meta)};queue.push(evt);if(queue.length>30)queue=queue.slice(-30);if(ready)flush()}
  async function flush(){if(flushing||!ready||!enabled||!queue.length)return;const r=R(),u=r?.state?.user;if(!u)return;flushing=true;const batch=queue.splice(0,12);try{const {error}=await r.sb.from('product_events').insert(batch);if(error)console.warn('RUMO analytics degraded',error.message)}catch(_){/* analytics never blocks product */}finally{flushing=false;if(queue.length)setTimeout(flush,800)}}
  function bind(){document.addEventListener('rumo:tab',e=>{const id=e.detail?.id||document.querySelector('.page.active')?.id||'';if(id&&id!==lastPage){lastPage=id;track('tab_viewed',{tab:id})}});document.addEventListener('click',e=>{if(e.target.closest?.('#open-ai,[data-tab="ia"]'))track('assistant_opened');if(e.target.closest?.('#account-integrations-v1'))track('integration_opened');if(e.target.closest?.('.contest-more'))track('contest_viewed');if(e.target.closest?.('#course-grid [data-course]'))track('course_opened')},true);window.addEventListener('error',e=>track('runtime_error',{kind:'error',file:String(e.filename||'').split('/').pop()||''}));window.addEventListener('unhandledrejection',()=>track('runtime_error',{kind:'promise'}));window.addEventListener('pagehide',flush)}
  document.addEventListener('rumo:context',()=>{const u=R()?.state?.user;if(!u){ready=true;enabled=false;return}if(!ready)loadPreference()});
  bind();setTimeout(()=>{if(R()?.state?.user)loadPreference();track('app_opened')},1600);
  window.RUMO_ANALYTICS={track,setEnabled,get enabled(){return enabled}};
})();
