(() => {
  'use strict';
  const R=()=>window.RUMO;
  let history=[];
  function weakPoints(){const s=R().state;return s.topicos.map(t=>{const q=(t.acertos||0)+(t.erros||0);return {...t,q,err:q?(t.erros||0)/q:0}}).filter(x=>x.q>=3).sort((a,b)=>b.err-a.err).slice(0,4)}
  function taskText(){const r=R(),tasks=r.state.tasks||[];if(!tasks.length)return'Não há tarefas pendentes no plano de hoje.';return tasks.filter(x=>!x.concluida).map((t,i)=>{const m=r.state.materias.find(x=>x.id===t.materia_id),tp=r.state.topicos.find(x=>x.id===t.topico_id);return `${i+1}. ${m?.nome||'Estudo'} — ${tp?.nome||t.titulo} (${t.minutos} min)`}).join('\n')||'Você concluiu todas as tarefas de hoje.'}
  async function adaptMinutes(total){const r=R(),pending=(r.state.tasks||[]).filter(x=>!x.concluida);if(!r.state.user||!pending.length)return false;const current=pending.reduce((a,x)=>a+x.minutos,0)||1;let used=0;for(let i=0;i<pending.length;i++){const m=i===pending.length-1?Math.max(10,total-used):Math.max(10,Math.round(total*(pending[i].minutos/current)/5)*5);used+=m;await r.sb.from('plano_tarefas').update({minutos:m}).eq('id',pending[i].id)}await window.RUMO_ENGINE?.loadTasks();return true}
  async function answer(raw){const r=R(),s=r.state,q=raw.trim(),low=q.toLowerCase();if(!q)return'';const minMatch=low.match(/(?:tenho|só tenho|so tenho)\s+(\d+(?:[.,]\d+)?)\s*(min|minutos?|h|hora|horas)/);if(minMatch){let n=parseFloat(minMatch[1].replace(',','.'));if(/^h|hora/.test(minMatch[2]))n*=60;n=Math.max(15,Math.round(n));const ok=await adaptMinutes(n);return ok?`Reorganizei as tarefas pendentes de hoje para caber em aproximadamente ${r.formatMinutes(n)}.\n\n${taskText()}`:`Você tem ${r.formatMinutes(n)}. Como ainda não há um plano salvo na sua conta, eu começaria com um bloco de conteúdo, um bloco curto de questões e 5–10 minutos de revisão.`}
    if(/o que.*estud|estud.*hoje|prioriz/.test(low))return `Seu próximo passo é este:\n\n${taskText()}\n\nComece pela primeira tarefa pendente. O objetivo é reduzir decisão, não aumentar a lista.`;
    if(/ponto.*fraco|fraque|mais erro|dificuldade/.test(low)){const w=weakPoints();if(!w.length)return'Você ainda não tem questões suficientes registradas para eu apontar um padrão confiável. Registre questões e erros durante as sessões; depois de algumas tentativas, os pontos fracos aparecem automaticamente.';return `Seus pontos mais frágeis agora são:\n\n${w.map((x,i)=>{const m=s.materias.find(y=>y.id===x.materia_id);return `${i+1}. ${m?.nome||'Matéria'} — ${x.nome}: ${Math.round(x.err*100)}% de erro em ${x.q} questões`}).join('\n')}\n\nEu aumentaria questões e revisões nesses tópicos antes de ampliar conteúdo novo.`}
    if(/reorgan|perdi.*dia|fiquei.*sem estudar|atrasei/.test(low)){await window.RUMO_ENGINE?.ensurePlan(true);return`Recalculei os próximos dias sem apagar o que você já concluiu. O RUMO preserva sessões feitas e redistribui as pendências dentro da sua rotina atual.\n\nHoje ficou assim:\n${taskText()}`}
    if(/quando.*prova|quanto.*falta|dias.*prova/.test(low)){const d=r.daysUntil(s.goal?.prova_data);return d===null?'A data da sua prova ainda não está definida no objetivo. Você pode ajustar isso em “Meu concurso”.':d>0?`Faltam ${d} dias para a prova de ${s.goal?.objective_name||'seu objetivo'}. Seu plano atual reserva ${Number(s.goal?.weekly_hours||0).toLocaleString('pt-BR')} horas por semana.`:d===0?'A prova é hoje. Priorize calma, logística e revisão leve — não tente reconstruir o conteúdo agora.':'A data cadastrada já passou. Atualize seu objetivo para eu recalcular o plano.'}
    if(/como estudar|método|metodo|memorizar|lembrar/.test(low))return'Use um ciclo simples: **aprender curto → tentar recuperar sem consultar → fazer questões → corrigir → revisar depois**. No RUMO, a sessão de estudo já segue essa lógica. Se um tópico tiver baixo acerto, o intervalo de revisão diminui; se estiver sólido, ele demora mais para voltar.';
    const topicCandidates=['crase','atos administrativos','interpretação de texto','interpretacao de texto','porcentagem','proposições','proposicoes','segurança da informação','seguranca da informacao','licitações','licitacoes','direitos fundamentais','excel'];const found=topicCandidates.find(x=>low.includes(x));if(found&&window.RUMO_SESSION)return window.RUMO_SESSION.explain('',found);
    if(/edital/.test(low))return s.user?'Você pode importar o PDF em “Meu concurso”. A leitura acontece no navegador e o RUMO tenta identificar matérias e tópicos para atualizar seu mapa e recalcular o plano. PDFs escaneados como imagem podem não ter texto suficiente.':'Entre na sua conta e abra “Meu concurso” para importar o edital e salvar o conteúdo.';
    return`Estou acompanhando ${s.goal?.objective_name||'seu estudo'}. Posso ser mais útil se você me pedir uma ação concreta, por exemplo:\n\n• “O que estudo hoje?”\n• “Tenho só 45 minutos.”\n• “Quais são meus pontos fracos?”\n• “Reorganize minha semana.”\n• “Explique crase.”`}
  function localAction(q){const low=q.toLowerCase();return /(?:tenho|só tenho|so tenho)\s+\d|o que.*estud|estud.*hoje|prioriz|ponto.*fraco|fraque|mais erro|reorgan|perdi.*dia|fiquei.*sem estudar|atrasei|quando.*prova|quanto.*falta|dias.*prova/.test(low)}
  function aiContext(){const r=R(),s=r.state,w=weakPoints();return {goal:s.goal?.objective_name||'',role:s.goal?.cargo||'',examDate:s.goal?.prova_data||'',weeklyHours:Number(s.goal?.weekly_hours)||0,tasks:(s.tasks||[]).filter(x=>!x.concluida).slice(0,6).map(t=>{const m=s.materias.find(x=>x.id===t.materia_id),tp=s.topicos.find(x=>x.id===t.topico_id);return `${m?.nome||'Estudo'} — ${tp?.nome||t.titulo} (${t.minutos} min)`}),weakPoints:w.map(x=>{const m=s.materias.find(y=>y.id===x.materia_id);return `${m?.nome||'Matéria'} — ${x.nome}: ${Math.round(x.err*100)}% de erro em ${x.q} questões`})}}
  async function remoteAnswer(q){const r=R();if(!r.state.user)throw new Error('login_required');const {data}=await r.sb.auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('session_missing');const res=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({question:q,context:aiContext(),history:history.slice(-6).map(x=>({role:x.role==='bot'?'assistant':'user',content:x.text}))})});const dataOut=await res.json().catch(()=>({}));if(!res.ok){const e=new Error(dataOut.error||'ai_unavailable');e.code=dataOut.error;e.limit=dataOut.limit;throw e}return dataOut.answer}
  async function smartAnswer(q){if(localAction(q))return answer(q);try{return await remoteAnswer(q)}catch(err){if(err?.code==='daily_limit')return`Você atingiu o limite de ${err.limit||20} mensagens de IA do beta hoje. As ações do RUMO continuam disponíveis normalmente; tente novamente amanhã.`;return answer(q)}}
  function formatMessage(text){return R().escapeHTML(text).replace(/\*\*(.*?)\*\*/g,'<b>$1</b>').replace(/\n/g,'<br>')}
  function buildPage(){const r=R(),host=r.qs('#ia .assistant');if(!host||host.dataset.v1)return;host.dataset.v1='1';host.innerHTML=`<div class="assistant-head"><div class="ai-orb">✦</div><div><b>Assistente RUMO</b><span>IA contextual · plano, desempenho e conteúdo</span></div><span class="beta-chip" style="margin-left:auto">BETA</span></div><div class="assistant-messages" id="assistant-messages-v1"></div><div class="chips compact"><button data-ai-prompt="O que eu estudo hoje?">O que estudar hoje?</button><button data-ai-prompt="Tenho só 45 minutos hoje">Tenho 45 minutos</button><button data-ai-prompt="Quais são meus pontos fracos?">Pontos fracos</button><button data-ai-prompt="Reorganize minha semana">Reorganizar semana</button></div><div class="chat"><input id="assistant-input-v1" placeholder="Pergunte sobre seu plano, desempenho ou conteúdo..."><button id="assistant-send-v1">↑</button></div>`;history=[];push('bot',`Olá. Eu vou usar seu objetivo${r.state.goal?` (${r.state.goal.objective_name})`:''}, seu plano e seu desempenho para orientar o próximo passo.`);r.qsa('[data-ai-prompt]',host).forEach(b=>b.onclick=()=>send(b.dataset.aiPrompt));r.qs('#assistant-send-v1').onclick=()=>send(r.qs('#assistant-input-v1').value);r.qs('#assistant-input-v1').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();send(e.target.value)}})}
  function push(role,text){const r=R(),box=r.qs('#assistant-messages-v1');if(!box)return;history.push({role,text});const el=document.createElement('div');el.className=`assistant-msg ${role}`;el.innerHTML=formatMessage(text);box.appendChild(el);box.scrollTop=box.scrollHeight}
  async function send(text){text=(text||'').trim();if(!text)return;const r=R(),input=r.qs('#assistant-input-v1');if(input)input.value='';push('user',text);const box=r.qs('#assistant-messages-v1'),thinking=document.createElement('div');thinking.className='assistant-msg bot assistant-thinking';thinking.textContent='Analisando seu RUMO...';box.appendChild(thinking);box.scrollTop=box.scrollHeight;try{const out=await smartAnswer(text);thinking.remove();push('bot',out)}catch(_){thinking.remove();push('bot','Não consegui concluir essa ação agora. Tente novamente em alguns segundos.') }}
  function bindModal(){const r=R(),modal=r.qs('#modal');if(!modal||modal.dataset.v1)return;modal.dataset.v1='1';const card=modal.querySelector('.modal-card');if(!card)return;const chats=card.querySelectorAll('.chat');chats.forEach(c=>{const input=c.querySelector('input'),btn=c.querySelector('button');if(btn)btn.onclick=async()=>{const q=input.value.trim();if(!q)return;input.value='';const p=document.createElement('div');p.className='explanation-box';p.innerHTML=formatMessage(await smartAnswer(q));c.before(p)}});card.querySelectorAll('.chips button').forEach(b=>b.onclick=async()=>{const p=document.createElement('div');p.className='explanation-box';p.innerHTML=formatMessage(await smartAnswer(b.textContent));card.querySelector('.chat')?.before(p)})}
  document.addEventListener('rumo:context',()=>setTimeout(()=>{buildPage();bindModal()},220));document.addEventListener('rumo:tasks',()=>{if(R().qs('#assistant-messages-v1')&&!history.length)buildPage()});setTimeout(()=>{if(R()?.state.ready){buildPage();bindModal()}},2200);window.RUMO_ASSISTANT={answer,smartAnswer,send};
})();