(() => {
  'use strict';
  const R=()=>window.RUMO;
  let cycle='monthly',subscription=null,loading=false;
  const active=()=>subscription?.plan==='pro'&&subscription?.status==='active';
  async function sessionToken(){const {data}=await R().sb.auth.getSession();return data.session?.access_token||null}
  async function load(){const r=R(),u=r.state.user;if(!u){subscription=null;paint();return null}const {data,error}=await r.sb.from('subscriptions').select('*').eq('user_id',u.id).maybeSingle();if(!error)subscription=data||null;paint();return subscription}
  function priceText(){return cycle==='annual'?'R$ 199/ano':'R$ 24,90/mês'}
  function paint(){const r=R(),modal=r.qs('#upgrade-modal'),card=modal?.querySelector('.pricing-modal');if(!card)return;const cards=[...card.querySelectorAll('.price-card')];cards.forEach((x,i)=>x.classList.toggle('selected',(i===0&&cycle==='monthly')||(i===1&&cycle==='annual')));let btn=card.querySelector('#billing-cta-v2')||card.querySelector('.primary.full');if(btn){btn.id='billing-cta-v2';if(active()){btn.textContent='RUMO Pro ativo';btn.disabled=true}else{btn.textContent=r.state.user?`Assinar · ${priceText()}`:'Entrar para assinar';btn.disabled=loading}}let status=card.querySelector('#billing-status-v2');if(!status){status=document.createElement('div');status.id='billing-status-v2';status.className='plan-readiness';btn?.after(status)}if(active())status.innerHTML=`<strong>PRO ATIVO</strong> Sua assinatura está ativa${subscription.current_period_end?` até ${new Date(subscription.current_period_end).toLocaleDateString('pt-BR')}`:''}.`;else if(subscription?.status==='pending')status.innerHTML='<strong>Pagamento pendente.</strong> Conclua o checkout do Mercado Pago para ativar o Pro.';else status.innerHTML='<strong>Beta continua liberado.</strong> A cobrança só acontece se você escolher assinar e concluir o checkout.';paintAccount()}
  function enhance(){const r=R(),card=r.qs('#upgrade-modal .pricing-modal');if(!card||card.dataset.billingV2)return;card.dataset.billingV2='1';const cards=[...card.querySelectorAll('.price-card')];cards.forEach((x,i)=>x.onclick=()=>{cycle=i===1?'annual':'monthly';paint()});const btn=card.querySelector('.primary.full');if(btn){btn.id='billing-cta-v2';btn.onclick=checkout}paint()}
  async function checkout(){const r=R();if(loading)return;if(!r.state.user){r.qs('#upgrade-modal')?.classList.remove('open');r.qs('#auth-v3')?.classList.add('open');return}const token=await sessionToken();if(!token){r.toast('Sua sessão expirou. Entre novamente.');return}loading=true;paint();window.RUMO_ANALYTICS?.track('checkout_started',{cycle});try{const res=await fetch('/api/checkout',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({cycle})});const data=await res.json().catch(()=>({}));if(res.status===503&&data.error==='billing_not_configured'){r.toast('Checkout ainda não está habilitado. O beta continua grátis.');window.RUMO_ANALYTICS?.track('checkout_unavailable');return}if(!res.ok||!data.checkout_url){r.toast('Não consegui abrir o checkout agora.');return}location.href=data.checkout_url}catch(_){r.toast('Não consegui conectar ao checkout agora.')}finally{loading=false;paint()}}
  function paintAccount(){const r=R(),actions=r.qs('#account-v3 .account-actions');if(!actions)return;let box=r.qs('#account-plan-v2');if(!box){box=document.createElement('div');box.id='account-plan-v2';box.style.cssText='padding:12px 14px;border:1px solid var(--line);border-radius:14px;margin-bottom:8px;font-size:13px';actions.prepend(box)}box.innerHTML=active()?`<b>RUMO Pro</b><div style="color:var(--muted);margin-top:3px">Assinatura ativa · ${subscription.billing_cycle==='annual'?'anual':'mensal'}</div>`:`<b>RUMO Free / Beta</b><div style="color:var(--muted);margin-top:3px">${subscription?.status==='pending'?'Checkout pendente':'Recursos liberados durante o beta'}</div>`;let cancel=r.qs('#account-cancel-pro-v2');if(active()&&!cancel){cancel=document.createElement('button');cancel.id='account-cancel-pro-v2';cancel.className='danger';cancel.textContent='Cancelar assinatura Pro';cancel.onclick=cancelSubscription;actions.insertBefore(cancel,r.qs('#account-logout-v3'))}else if(!active()&&cancel)cancel.remove()}
  async function cancelSubscription(){const r=R();if(!active())return;if(!confirm('Cancelar a assinatura RUMO Pro?'))return;const token=await sessionToken();if(!token)return;r.toast('Cancelando assinatura...');const res=await fetch('/api/cancel-subscription',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:'{}'});if(res.ok){r.toast('Assinatura cancelada.');await load()}else r.toast('Não consegui cancelar agora. Tente novamente.')}
  async function reconcileReturn(){if(!new URLSearchParams(location.search).has('billing'))return;history.replaceState({},'',location.pathname+location.hash);R().toast('Pagamento recebido. Atualizando sua assinatura...');for(let i=0;i<3;i++){await new Promise(x=>setTimeout(x,1200+i*700));await load();if(active()){R().toast('RUMO Pro ativado.');break}}}
  document.addEventListener('rumo:context',()=>{enhance();load();setTimeout(reconcileReturn,0)});document.addEventListener('click',e=>{if(e.target.closest?.('#upgrade-btn'))setTimeout(()=>{enhance();paint()},0);if(e.target.closest?.('#account-btn'))setTimeout(paintAccount,0)},true);enhance();
  window.RUMO_BILLING={load,isPro:active,get subscription(){return subscription}};
})();
