(() => {
  'use strict';
  const R=()=>window.RUMO;let cycle='monthly';
  function enhancePricing(){const r=R(),modal=r.qs('#upgrade-modal');if(!modal)return;const card=modal.querySelector('.pricing-modal');if(!card||card.dataset.v1)return;card.dataset.v1='1';const title=card.querySelector('h2');if(title)title.textContent='Escolha seu RUMO sem pagar caro.';const p=card.querySelector('p');if(p)p.textContent='Durante o beta, os recursos estão liberados para teste. No lançamento, o Pro poderá ser mensal ou anual e o pagamento acontecerá dentro da plataforma.';const priceCards=[...card.querySelectorAll('.price-card')];priceCards.forEach((x,i)=>{x.onclick=()=>{priceCards.forEach(y=>y.classList.remove('selected'));x.classList.add('selected');cycle=i===0?'monthly':'annual'}});const btn=card.querySelector('.primary.full');if(btn){btn.textContent='Usar o beta grátis';btn.onclick=()=>{localStorage.setItem('rumo-beta-interest',cycle);modal.classList.remove('open');r.toast('Beta liberado. Nenhuma cobrança foi feita.')}}const note=document.createElement('div');note.className='plan-readiness';note.innerHTML='<strong>Checkout preparado para a próxima fase.</strong> A estrutura de assinatura já existe no banco, mas não vamos pedir pagamento enquanto o produto ainda estiver em validação.';btn?.after(note)}
  function addRecovery(){const r=R(),form=r.qs('#auth-form');if(!form||r.qs('#forgot-password-v1'))return;const b=document.createElement('button');b.type='button';b.id='forgot-password-v1';b.className='soft-btn';b.style.cssText='border:0;background:transparent;padding:4px 0;text-align:left;color:var(--accent);justify-self:start';b.textContent='Esqueci minha senha';const password=r.qs('#auth-password')?.closest('.field');password?.after(b);b.onclick=async()=>{const email=r.qs('#auth-email').value.trim();if(!email){r.qs('#auth-message').textContent='Digite seu e-mail primeiro.';return}const {error}=await r.sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin});r.qs('#auth-message').className=`form-message ${error?'error':'success'}`;r.qs('#auth-message').textContent=error?'Não consegui enviar o e-mail agora.':'Enviamos um link de recuperação para seu e-mail.'}}
  function recoveryModal(){const r=R();if(r.qs('#recovery-v1'))return;document.body.insertAdjacentHTML('beforeend',`<div id="recovery-v1" class="modal"><div class="modal-card auth-shell"><div class="eyebrow">NOVA SENHA</div><h2>Crie uma nova senha.</h2><form id="recovery-form-v1" class="form-grid"><div class="field"><label>Nova senha</label><input id="recovery-password-v1" type="password" minlength="6" required placeholder="Mínimo de 6 caracteres"></div><div id="recovery-message-v1" class="form-message"></div><button class="primary" type="submit">Atualizar senha</button></form></div></div>`);r.qs('#recovery-form-v1').onsubmit=async e=>{e.preventDefault();const pass=r.qs('#recovery-password-v1').value,msg=r.qs('#recovery-message-v1');const {error}=await r.sb.auth.updateUser({password:pass});msg.className=`form-message ${error?'error':'success'}`;msg.textContent=error?'Não consegui atualizar a senha.':'Senha atualizada.';if(!error)setTimeout(()=>r.qs('#recovery-v1').classList.remove('open'),500)}}
  function footer(){const r=R(),f=r.qs('.eden-footer');if(!f||f.dataset.v1)return;f.dataset.v1='1';f.innerHTML=`<span>EDEN</span><div style="margin-top:7px;letter-spacing:0;display:flex;justify-content:center;gap:8px"><a href="./privacidade.html" style="color:inherit;text-decoration:none">Privacidade</a><a href="./termos.html" style="color:inherit;text-decoration:none">Termos</a></div>`}
  function boot(){enhancePricing();addRecovery();recoveryModal();footer();R().sb.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')R().qs('#recovery-v1')?.classList.add('open')})}
  setTimeout(boot,2300);document.addEventListener('rumo:context',()=>setTimeout(()=>{enhancePricing();addRecovery()},100));
})();