(() => {
  'use strict';
  const R=()=>window.RUMO;
  let courses=[],filteredCourses=[],activeCategory='all',query='',detailCache=new Map(),cloud=new Map(),cloudLoadedFor=null;
  const localKey='rumo-content-progress-v1';
  const esc=s=>R()?.escapeHTML?R().escapeHTML(String(s??'')):String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function localState(){try{return JSON.parse(localStorage.getItem(localKey)||'{}')}catch(_){return{}}}
  function saveLocal(v){localStorage.setItem(localKey,JSON.stringify(v))}
  function stateFor(id){const local=localState()[id]||{},remote=cloud.get(id)||{};const done=[...new Set([...(Array.isArray(remote.done_lessons)?remote.done_lessons:[]),...(Array.isArray(local.done)?local.done:[])].filter(x=>typeof x==='string'&&x.length>10))];return{done,last:local.last||null}}
  async function loadCloud(){const r=R(),uid=r?.state?.user?.id||null;if(!uid){cloud.clear();cloudLoadedFor=null;return}if(cloudLoadedFor===uid)return;const {data}=await r.sb.from('course_progress').select('course_id,progress,done_lessons').eq('user_id',uid);cloud=new Map((data||[]).map(x=>[x.course_id,x]));cloudLoadedFor=uid}
  async function persist(courseId,lessonId,total){const r=R(),data=localState(),st=stateFor(courseId);if(!st.done.includes(lessonId))st.done.push(lessonId);data[courseId]={done:st.done,last:lessonId};saveLocal(data);const pct=Math.round(st.done.length/Math.max(1,total)*100);if(r?.state?.user){const {error}=await r.sb.from('course_progress').upsert({user_id:r.state.user.id,course_id:courseId,progress:pct,done_lessons:st.done,last_lesson:0,updated_at:new Date().toISOString()},{onConflict:'user_id,course_id'});if(!error)cloud.set(courseId,{course_id:courseId,progress:pct,done_lessons:st.done})}renderCards();return pct}
  function progress(id,total){if(!total)return 0;return Math.round(stateFor(id).done.length/total*100)}
  function injectToolbar(){const page=document.querySelector('#essenciais');if(!page||page.querySelector('.content-library-bar'))return;const grid=page.querySelector('#course-grid');if(!grid)return;const bar=document.createElement('div');bar.className='content-library-bar';bar.innerHTML='<div class="content-search"><span>⌕</span><input id="content-search-v1" placeholder="Buscar matéria ou trilha..."></div><div class="content-stats"><span><b id="content-course-count">0</b> trilhas</span><span><b id="content-lesson-count">0</b> aulas</span></div>';grid.before(bar);bar.querySelector('input').addEventListener('input',e=>{query=e.target.value.toLowerCase().trim();applyFilters()})}
  function cardHTML(c){const pct=progress(c.id,c.lesson_count||0);return `<article class="course content-course" data-content-course="${esc(c.id)}" data-course="${esc(c.id)}" style="--course-accent:${esc(c.accent||'#3677ff')}"><div class="course-top"><div class="course-icon">${esc(c.icon||'•')}</div><span class="course-tag">${c.lesson_count||0} AULAS</span></div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><div class="course-info"><span>${c.estimated_days||7} dias</span><span>${c.minutes_per_day||20} min/dia</span></div>${pct?`<div class="course-progress"><div class="line"><i style="width:${pct}%"></i></div><small>${pct}% concluído</small></div>`:''}</article>`}
  function applyFilters(){filteredCourses=courses.filter(c=>(activeCategory==='all'||c.category===activeCategory)&&(!query||`${c.title} ${c.description} ${c.level||''}`.toLowerCase().includes(query)));renderCards()}
  function renderCards(){const grid=document.querySelector('#course-grid');if(!grid)return;grid.innerHTML=filteredCourses.length?filteredCourses.map(cardHTML).join(''):'<div class="content-empty">Nenhuma trilha encontrada com este filtro.</div>';document.querySelector('#content-course-count')&&(document.querySelector('#content-course-count').textContent=courses.length);document.querySelector('#content-lesson-count')&&(document.querySelector('#content-lesson-count').textContent=courses.reduce((a,c)=>a+(c.lesson_count||0),0))}
  function bindFilters(){document.querySelectorAll('.course-filter').forEach(btn=>{btn.onclick=()=>{document.querySelectorAll('.course-filter').forEach(x=>x.classList.toggle('active',x===btn));activeCategory=btn.dataset.courseFilter||'all';applyFilters()}})}
  async function loadCourses(){const r=R();if(!r?.sb)return;await loadCloud();const {data,error}=await r.sb.from('content_courses').select('*').order('order_index',{ascending:true});if(error)throw error;const list=data||[];const withCounts=await Promise.all(list.map(async c=>{const {data:mods}=await r.sb.from('content_modules').select('id').eq('course_id',c.id);const mids=(mods||[]).map(x=>x.id);let count=0;if(mids.length){const {count:n}=await r.sb.from('content_lessons').select('id',{count:'exact',head:true}).in('module_id',mids);count=n||0}return {...c,lesson_count:count}}));courses=withCounts;filteredCourses=[...courses];injectToolbar();bindFilters();applyFilters()}
  function paragraphs(text){return String(text||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean).map(p=>`<p>${esc(p)}</p>`).join('')}
  async function detail(courseId){if(detailCache.has(courseId))return detailCache.get(courseId);const r=R();const [{data:course},{data:modules,error:me}]=await Promise.all([r.sb.from('content_courses').select('*').eq('id',courseId).single(),r.sb.from('content_modules').select('*').eq('course_id',courseId).order('order_index')]);if(me)throw me;const mids=(modules||[]).map(x=>x.id);let lessons=[];if(mids.length){const {data,error}=await r.sb.from('content_lessons').select('*').in('module_id',mids).order('order_index');if(error)throw error;lessons=data||[]}const lids=lessons.map(x=>x.id);let questions=[],sources=[];if(lids.length){const [q,s]=await Promise.all([r.sb.from('content_questions').select('*').in('lesson_id',lids).order('order_index'),r.sb.from('content_sources').select('*').in('lesson_id',lids)]);questions=q.data||[];sources=s.data||[]}const out={course,modules:modules||[],lessons,questions,sources};detailCache.set(courseId,out);return out}
  function orderedLessons(d){const mo=new Map(d.modules.map((m,i)=>[m.id,[m.order_index??i,i]]));return [...d.lessons].sort((a,b)=>{const ma=mo.get(a.module_id)||[0,0],mb=mo.get(b.module_id)||[0,0];return ma[0]-mb[0]||ma[1]-mb[1]||(a.order_index||0)-(b.order_index||0)})}
  function outlineHTML(d,activeId){const done=new Set(stateFor(d.course.id).done);return d.modules.map(m=>{const ls=d.lessons.filter(l=>l.module_id===m.id).sort((a,b)=>(a.order_index||0)-(b.order_index||0));return `<div class="content-module"><strong>${esc(m.title)}</strong>${ls.map((l,i)=>`<button class="content-lesson-btn ${l.id===activeId?'active':''} ${done.has(l.id)?'done':''}" data-content-lesson="${esc(l.id)}"><span class="lesson-dot">${done.has(l.id)?'✓':i+1}</span><span>${esc(l.title)}</span><small>${l.estimated_minutes||15}m</small></button>`).join('')}</div>`}).join('')}
  function sourcesHTML(d,lessonId){const list=d.sources.filter(x=>x.lesson_id===lessonId);if(!list.length)return'';return `<div class="content-sources"><h3>FONTES E REFERÊNCIAS</h3>${list.map(s=>`<div class="content-source"><span>↗</span>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a>`:esc(s.title)}<span>· ${esc(s.publisher||'RUMO')}</span></div>`).join('')}</div>`}
  function questionHTML(d,lessonId){const q=d.questions.find(x=>x.lesson_id===lessonId);if(!q)return'';const opts=Array.isArray(q.options)?q.options:[];return `<div class="content-question" data-question="${esc(q.id)}"><small>QUESTÃO RÁPIDA</small><h3>${esc(q.prompt)}</h3><div class="content-options">${opts.map(o=>`<button class="content-option" data-answer="${esc(o)}">${esc(o)}</button>`).join('')}</div><div class="content-explanation"><b>Comentário:</b> ${esc(q.explanation)}</div></div>`}
  function renderLesson(d,lessonId){const host=document.querySelector('#course-modal-content');const lesson=d.lessons.find(x=>x.id===lessonId)||orderedLessons(d)[0];if(!host||!lesson)return;const all=orderedLessons(d),idx=all.findIndex(x=>x.id===lesson.id),done=new Set(stateFor(d.course.id).done),pct=progress(d.course.id,d.lessons.length);host.innerHTML=`<div class="content-shell"><aside class="content-outline"><div class="content-course-head" style="--accent:${esc(d.course.accent||'#3677ff')}"><div class="content-icon">${esc(d.course.icon||'•')}</div><h2>${esc(d.course.title)}</h2><p>${esc(d.course.description)}</p><div class="content-course-progress"><div class="line"><i style="width:${pct}%"></i></div><small>${pct}% concluído</small></div></div>${outlineHTML(d,lesson.id)}</aside><section class="content-reader"><div class="content-reader-inner"><div class="eyebrow">${esc(d.modules.find(m=>m.id===lesson.module_id)?.title||'AULA')}</div><h2>${esc(lesson.title)}</h2><p class="content-summary">${esc(lesson.summary)}</p><div class="content-meta-row"><span class="content-pill">${esc(lesson.difficulty||'básico')}</span><span class="content-pill">${lesson.estimated_minutes||15} min</span></div>${lesson.objective?`<div class="content-objective"><b>OBJETIVO</b><p>${esc(lesson.objective)}</p></div>`:''}<div class="content-block"><h3>ENTENDA</h3>${paragraphs(lesson.content_md)}</div>${lesson.example_md?`<div class="content-block content-example"><h3>EXEMPLO</h3>${paragraphs(lesson.example_md)}</div>`:''}${lesson.pitfalls_md?`<div class="content-block content-pitfalls"><h3>ATENÇÃO NA PROVA</h3>${paragraphs(lesson.pitfalls_md)}</div>`:''}${lesson.recap_md?`<div class="content-block content-recap"><h3>RESUMO DE 20 SEGUNDOS</h3>${paragraphs(lesson.recap_md)}</div>`:''}${questionHTML(d,lesson.id)}${sourcesHTML(d,lesson.id)}<div class="content-actions"><button class="secondary" id="content-prev" ${idx<=0?'disabled':''}>← Anterior</button><button class="primary content-complete ${done.has(lesson.id)?'done':''}" id="content-complete">${done.has(lesson.id)?'✓ Concluída':'Concluir e continuar'}</button></div></div></section></div>`;
    host.querySelectorAll('[data-content-lesson]').forEach(b=>b.onclick=()=>renderLesson(d,b.dataset.contentLesson));
    host.querySelector('#content-prev')?.addEventListener('click',()=>idx>0&&renderLesson(d,all[idx-1].id));
    host.querySelector('#content-complete')?.addEventListener('click',async()=>{await persist(d.course.id,lesson.id,d.lessons.length);if(idx<all.length-1)renderLesson(d,all[idx+1].id);else{renderLesson(d,lesson.id);R()?.toast?.('Trilha concluída. Excelente fechamento.')}});
    const q=d.questions.find(x=>x.lesson_id===lesson.id);if(q){host.querySelectorAll('.content-option').forEach(btn=>btn.onclick=()=>{const box=btn.closest('.content-question');if(box.dataset.answered)return;box.dataset.answered='1';box.querySelectorAll('.content-option').forEach(o=>{if(o.dataset.answer===q.correct_answer)o.classList.add('correct')});if(btn.dataset.answer!==q.correct_answer)btn.classList.add('wrong');box.querySelector('.content-explanation')?.classList.add('show')})}
  }
  async function open(courseId){const modal=document.querySelector('#course-modal'),host=document.querySelector('#course-modal-content');if(!modal||!host)return;modal.classList.add('open');host.innerHTML='<div class="content-loader">Carregando trilha...</div>';try{await loadCloud();const d=await detail(courseId);const st=stateFor(courseId),first=(st.last&&d.lessons.some(l=>l.id===st.last))?st.last:orderedLessons(d).find(l=>!st.done.includes(l.id))?.id||orderedLessons(d)[0]?.id;renderLesson(d,first)}catch(e){console.warn('RUMO content',e);host.innerHTML='<div class="content-loader">Não foi possível carregar esta trilha agora.</div>'}}
  document.addEventListener('click',e=>{const card=e.target.closest?.('[data-content-course]');if(card){e.preventDefault();e.stopImmediatePropagation();open(card.dataset.contentCourse)}},true);
  document.addEventListener('rumo:tab',e=>{if(e.detail?.id==='essenciais'&&!courses.length)loadCourses().catch(err=>console.warn('content library',err))});
  document.addEventListener('rumo:data-ready',()=>loadCloud().then(renderCards).catch(()=>{}));
  injectToolbar();bindFilters();loadCourses().catch(err=>{console.warn('RUMO content init',err);const grid=document.querySelector('#course-grid');if(grid)grid.innerHTML='<div class="content-empty">Biblioteca temporariamente indisponível.</div>'});
  window.RUMO_CONTENT={open,reload:()=>{detailCache.clear();courses=[];return loadCourses()}};
})();
