(() => {
  'use strict';
  const URL='https://zycpeiyztqysjqejtour.supabase.co',KEY='sb_publishable_heHXvAxo36EvgHg_8_XOXQ_rRxE5t5H';
  if(!window.supabase)return;
  const sb=window.supabase.createClient(URL,KEY),state={user:null,goal:null,contest:null,userConcurso:null,materias:[],topicos:[],tasks:[],ready:false};
  const qs=(s,r=document)=>r.querySelector(s),qsa=(s,r=document)=>[...r.querySelectorAll(s)],escapeHTML=(s='')=>String(s).replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#039;','"':'&quot;'}[m]));
  const today=()=>{const d=new Date();return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},addDays=(iso,n)=>{const d=new Date(`${iso}T12:00:00`);d.setDate(d.getDate()+n);return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},formatMinutes=m=>{m=Math.max(0,Math.round(Number(m)||0));const h=Math.floor(m/60),min=m%60;return h?`${h}h${min?String(min).padStart(2,'0'):''}`:`${min}min`},daysUntil=iso=>{if(!iso)return null;const d=new Date(`${iso}T12:00:00`),n=new Date();n.setHours(0,0,0,0);return Math.ceil((d-n)/86400000)};
  function toast(msg){let e=qs('.rumo-toast');if(!e){e=document.createElement('div');e.className='rumo-toast';document.body.appendChild(e)}e.textContent=msg;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2500)}
  const emit=(name,detail={})=>document.dispatchEvent(new CustomEvent(`rumo:${name}`,{detail}));
  const templates={
    fiscal:[['Português',1.15,['Interpretação de texto','Concordância e regência','Crase e pontuação','Reescrita e coesão']],['Raciocínio Lógico',1.05,['Proposições e conectivos','Porcentagem e razão','Probabilidade','Problemas lógicos']],['Direito Constitucional',1.1,['Direitos fundamentais','Administração Pública','Organização do Estado','Poderes']],['Direito Administrativo',1.1,['Princípios','Atos administrativos','Poderes','Licitações e contratos']],['Direito Tributário',1.35,['Sistema Tributário Nacional','Competência tributária','Obrigação tributária','Crédito tributário','Impostos']],['Contabilidade',1.5,['Patrimônio e contas','Escrituração','Demonstrações contábeis','Análise das demonstrações']],['Tecnologia da Informação',.85,['Segurança da informação','Redes','Banco de dados','Planilhas','Dados e IA']]],
    seguranca:[['Português',1.2,['Interpretação','Gramática aplicada','Concordância e regência','Crase']],['Raciocínio Lógico',.9,['Proposições','Equivalências','Porcentagem','Problemas']],['Informática',.85,['Sistemas operacionais','Internet','Redes','Segurança','Office']],['Direito Constitucional',1.15,['Direitos fundamentais','Segurança pública','Administração Pública','Organização do Estado']],['Direito Administrativo',1.05,['Princípios','Atos','Poderes','Agentes públicos']],['Direito Penal',1.35,['Lei penal','Teoria do crime','Crimes contra a pessoa','Crimes contra o patrimônio','Crimes contra a Administração']],['Processo Penal',1.25,['Inquérito','Ação penal','Provas','Prisões e cautelares']],['Legislação Especial',1.25,['Leis penais especiais','Direitos humanos','Legislação institucional','Abuso de autoridade']]],
    tribunais:[['Português',1.35,['Interpretação','Reescrita','Concordância e regência','Crase','Pontuação']],['Raciocínio Lógico',.85,['Proposições','Porcentagem','Probabilidade','Sequências']],['Informática',.75,['Sistemas operacionais','Office','Internet','Segurança']],['Direito Constitucional',1.2,['Direitos fundamentais','Organização do Estado','Poder Judiciário','Administração Pública']],['Direito Administrativo',1.2,['Princípios','Atos','Poderes','Agentes','Licitações']],['Legislação',1.15,['Regimento interno','Normas institucionais','Ética','Proteção de dados']]],
    administrativa:[['Português',1.3,['Interpretação','Gramática aplicada','Concordância e regência','Crase e pontuação','Redação oficial']],['Raciocínio Lógico',1,['Proposições','Porcentagem','Razão e proporção','Estatística básica']],['Informática',1.05,['Windows e arquivos','Office','Internet','Segurança','Nuvem']],['Direito Administrativo',1.15,['Princípios','Atos','Poderes','Agentes','Licitações']],['Direito Constitucional',.95,['Direitos fundamentais','Administração Pública','Organização do Estado','Poderes']],['Administração Pública',1.05,['Gestão pública','Processos','Atendimento','Arquivologia','Ética']]],
    educacao:[['Português',1.1,['Interpretação','Gramática aplicada','Coesão','Redação']],['Legislação Educacional',1.35,['LDB','PNE','Diretrizes curriculares','Inclusão e diversidade']],['Conhecimentos Pedagógicos',1.45,['Didática','Avaliação','Currículo','Planejamento','Aprendizagem']],['Informática',.7,['Ferramentas digitais','Office','Internet','Segurança']],['Conhecimentos Específicos',1.5,['Fundamentos da área','Conteúdo programático','Metodologia','Questões da banca']]],
    saude:[['Português',.85,['Interpretação','Gramática','Coesão','Pontuação']],['SUS e Saúde Pública',1.35,['Princípios do SUS','Leis 8.080 e 8.142','Políticas públicas','Vigilância em saúde']],['Informática',.6,['Office','Internet','Segurança','Dados']],['Ética e Legislação',1,['Ética profissional','Legislação da profissão','Segurança do paciente','Direitos do usuário']],['Conhecimentos Específicos',1.6,['Fundamentos técnicos','Protocolos','Procedimentos','Casos práticos']]],
    vestibular:[['Linguagens',1.2,['Interpretação','Gramática e linguagem','Literatura','Inglês ou Espanhol']],['Matemática',1.4,['Aritmética e porcentagem','Álgebra','Geometria','Funções','Probabilidade e estatística']],['Redação',1.45,['Estrutura dissertativa','Tese','Argumentação','Repertório','Coesão']],['Ciências Humanas',1.05,['História','Geografia','Filosofia','Sociologia']],['Ciências da Natureza',1.25,['Biologia','Química','Física','Interdisciplinaridade']]],
    geral:[['Português',1.3,['Interpretação','Gramática aplicada','Concordância e regência','Crase e pontuação','Reescrita']],['Raciocínio Lógico',1,['Proposições','Porcentagem','Razão e proporção','Probabilidade','Problemas']],['Informática',.95,['Sistemas operacionais','Office','Internet','Redes','Segurança']],['Direito Administrativo',1.05,['Princípios','Atos','Poderes','Agentes','Licitações']],['Direito Constitucional',1,['Direitos fundamentais','Administração Pública','Organização do Estado','Poderes']]]
  };
  function templateKey(goal,contest){const t=`${goal?.objective_name||''} ${goal?.cargo||''} ${contest?.area||''}`.toLowerCase();if(/enem|vestibular|fuvest|unesp|unicamp/.test(t))return'vestibular';if(/sefaz|fiscal|auditor|receita|tribut/.test(t))return'fiscal';if(/polícia|policia|segurança|seguranca|\bpf\b|\bprf\b|delegado|perícia|pericia/.test(t))return'seguranca';if(/tribunal|trt|trf|\btj\b|\btre\b|tse|judici/.test(t))return'tribunais';if(/educa|professor|seduc|pedagog/.test(t))return'educacao';if(/saúde|saude|enferm|médic|medic|cofen/.test(t))return'saude';if(/administra|prefeitura|transpetro|inb|detran/.test(t))return'administrativa';return'geral'}
  let syncing=null,lastSync=0;
  async function loadStructure(){if(!state.userConcurso){state.materias=[];state.topicos=[];return}let {data:mats}=await sb.from('materias').select('*').eq('user_concurso_id',state.userConcurso.id).order('peso',{ascending:false});if(!mats?.length){const tpl=templates[templateKey(state.goal,state.contest)],created=await sb.from('materias').insert(tpl.map(([nome,peso])=>({user_concurso_id:state.userConcurso.id,nome,peso,prioridade:peso>=1.3?'alta':peso>=1.05?'media':'baixa'}))).select();mats=created.data||[];const topicRows=[];for(const m of mats){const def=tpl.find(x=>x[0]===m.nome);for(const nome of def?.[2]||[])topicRows.push({materia_id:m.id,nome})}if(topicRows.length)await sb.from('topicos').insert(topicRows)}state.materias=mats||[];if(state.materias.length){const {data}=await sb.from('topicos').select('*').in('materia_id',state.materias.map(x=>x.id)).order('criado_em');state.topicos=data||[]}else state.topicos=[]}
  async function refreshStructure(){await loadStructure();emit('structure',{state});return state}
  async function doSync(){const {data:sessionData}=await sb.auth.getSession();state.user=sessionData.session?.user||null;state.contest=null;state.userConcurso=null;if(!state.user){try{state.goal=JSON.parse(localStorage.getItem('rumo-guest-goal')||'null')}catch(_){state.goal=null}state.materias=[];state.topicos=[];state.ready=true;lastSync=Date.now();emit('context',{state});return state}const {data:goal}=await sb.from('user_goals').select('*').eq('user_id',state.user.id).eq('active',true).order('created_at',{ascending:false}).limit(1).maybeSingle();state.goal=goal||null;if(!state.goal){state.materias=[];state.topicos=[];state.ready=true;lastSync=Date.now();emit('context',{state});return state}const contestQ=state.goal.concurso_id?sb.from('concursos').select('*').eq('id',state.goal.concurso_id).maybeSingle():sb.from('concursos').select('*').ilike('nome',state.goal.objective_name).limit(1),ucQ=sb.from('user_concursos').select('*').eq('user_id',state.user.id).eq('principal',true).order('criado_em',{ascending:false}).limit(1).maybeSingle();const [contestRes,ucRes]=await Promise.all([contestQ,ucQ]);state.contest=state.goal.concurso_id?(contestRes.data||null):(contestRes.data?.[0]||null);if(state.contest&&!state.goal.concurso_id){state.goal.concurso_id=state.contest.id;sb.from('user_goals').update({concurso_id:state.contest.id}).eq('id',state.goal.id).then(()=>{})}const patch={cargo:state.goal.cargo||null,prova_data:state.goal.prova_data||null,concurso_id:state.goal.concurso_id||null};if(ucRes.data){state.userConcurso={...ucRes.data,...patch};await sb.from('user_concursos').update(patch).eq('id',ucRes.data.id)}else{const {data}=await sb.from('user_concursos').insert({user_id:state.user.id,...patch,principal:true}).select().single();state.userConcurso=data||null}await loadStructure();state.ready=true;lastSync=Date.now();emit('context',{state});return state}
  function sync(force=false){if(syncing)return syncing;if(!force&&state.ready&&Date.now()-lastSync<15000)return Promise.resolve(state);syncing=doSync().finally(()=>{syncing=null});return syncing}
  window.RUMO={sb,state,qs,qsa,escapeHTML,today,addDays,formatMinutes,daysUntil,toast,emit,templates,templateKey,sync,refreshStructure};

  // Supabase holds an internal auth lock while this callback runs. Re-entering
  // auth APIs (getSession) synchronously from here can deadlock an existing login.
  // Always return first, then synchronize on the next task.
  let authTimer=null;
  sb.auth.onAuthStateChange((event,session)=>{
    state.user=session?.user||null;
    if(event==='INITIAL_SESSION')return;
    clearTimeout(authTimer);
    authTimer=setTimeout(()=>{sync(true).catch(err=>console.warn('RUMO auth sync failed',err))},0);
  });
})();