(() => {
  'use strict';
  const R=()=>window.RUMO;
  const courses={
    informatica:{title:'Informática Essencial',lessons:[
      ['Seu computador sem mistério','Sistema operacional é a camada que organiza arquivos, programas, dispositivos e sua interação com a máquina. Para trabalhar bem, domine janelas, área de trabalho, pesquisa, configurações e atalhos básicos.','Prática: abra o Explorador de Arquivos, crie uma pasta chamada RUMO, dentro dela crie duas subpastas e mova um arquivo entre elas.'],
      ['Arquivos, pastas e formatos','O nome do arquivo ajuda a identificar o conteúdo; a extensão indica o formato. PDF, DOCX, XLSX, JPG e ZIP têm funções diferentes. Copiar cria outra versão; mover altera o local. A Lixeira não substitui backup.','Prática: identifique a extensão de cinco arquivos no seu computador e explique o que cada formato costuma armazenar.'],
      ['Internet, navegador e pesquisa','Navegador é o programa usado para acessar páginas; mecanismo de busca é o serviço que encontra conteúdo. URL, domínio, HTTPS, abas, downloads e favoritos aparecem tanto no trabalho quanto em provas.','Prática: faça uma busca usando aspas para uma expressão exata e outra usando site:gov.br. Compare os resultados.'],
      ['E-mail, nuvem e colaboração','E-mail profissional exige assunto claro, mensagem objetiva e cuidado com anexos. Nuvem permite armazenar e sincronizar arquivos, mas sincronização não é sinônimo de backup. Permissões definem quem pode visualizar ou editar.','Prática: escreva um e-mail de três linhas pedindo confirmação de recebimento de um documento, com assunto e despedida adequados.'],
      ['Segurança digital básica','Senhas únicas, autenticação em dois fatores, atualizações e desconfiança de links inesperados reduzem muito o risco. Phishing tenta induzir você a entregar informação ou executar uma ação.','Prática: revise três contas importantes e confirme se usam senha única e autenticação em dois fatores.'],
      ['Atalhos que economizam tempo','Atalhos reduzem repetição. Ctrl+C/V/X copiam, colam e recortam; Ctrl+Z desfaz; Ctrl+F busca; Alt+Tab alterna janelas; Win+Shift+S captura uma área da tela no Windows.','Prática: durante 10 minutos, tente executar copiar, colar, buscar e alternar janelas sem usar o mouse.']
    ]},
    excel:{title:'Excel Essencial',lessons:[
      ['Planilha, célula e referência','Uma planilha organiza dados em linhas e colunas. Cada célula possui endereço, como A1. Fórmulas começam com = e podem usar valores ou referências. Organizar a base corretamente é mais importante do que decorar dezenas de funções.','Prática: crie uma tabela com Produto, Quantidade e Preço para cinco itens.'],
      ['SOMA, MÉDIA e porcentagem','=SOMA(A1:A5) agrega valores; =MÉDIA(A1:A5) calcula a média. Para calcular 15% de B2, use =B2*15%. Referências permitem alterar os dados sem refazer a conta.','Prática: calcule total, média de preços e um desconto de 10% para sua tabela.'],
      ['Função SE','SE testa uma condição: =SE(B2>=7;"Aprovado";"Revisar"). Pense sempre em três partes: condição, resultado se verdadeiro e resultado se falso.','Prática: crie uma coluna Status que mostre “Meta atingida” quando a quantidade for 10 ou mais.'],
      ['Filtros e tabelas','Filtros escondem temporariamente linhas que não atendem a um critério. Transformar uma base em Tabela ajuda na leitura, expansão e fórmulas. Evite linhas vazias e células mescladas dentro da base de dados.','Prática: filtre sua tabela para mostrar apenas itens acima de determinado preço.'],
      ['Gráficos que comunicam','Gráfico deve responder uma pergunta. Barras funcionam bem para comparar categorias; linhas, para evolução no tempo; pizza só faz sentido para poucas partes de um total. Menos elementos decorativos geralmente melhora a leitura.','Prática: crie um gráfico de barras com os preços dos itens e dê um título que explique o que está sendo comparado.'],
      ['PROCX e busca de dados','PROCX procura um valor em uma coluna e retorna o correspondente de outra. A lógica é: o que procurar, onde procurar e o que devolver. Em versões antigas, PROCV cumpre parte desse papel com mais limitações.','Prática: faça uma pequena tabela de códigos e preços e use PROCX para retornar o preço a partir do código.']
    ]},
    portugues:{title:'Português para Provas',lessons:[
      ['Interpretação antes da gramática','Leia o comando antes de julgar alternativas. Diferencie informação explícita, inferência permitida e opinião que não está sustentada pelo texto. Muitas questões erradas parecem verdadeiras fora do texto, mas não respondem ao que foi apresentado.','Prática: pegue uma notícia curta e escreva em uma frase a tese principal e em outra uma inferência possível.'],
      ['Concordância','Na concordância verbal, o verbo se relaciona com o núcleo do sujeito. Expressões longas entre sujeito e verbo são usadas para provocar distração. Na nominal, adjetivos e determinantes se ajustam ao substantivo conforme a estrutura.','Prática: encontre o núcleo do sujeito em cinco frases antes de escolher a forma verbal.'],
      ['Regência','Regência trata da relação entre um termo e seus complementos, inclusive a preposição exigida. Verbos como assistir, preferir, obedecer e visar costumam aparecer em questões por terem usos específicos na norma-padrão.','Prática: monte uma frase correta com “assistir” no sentido de ver e outra com “obedecer”.'],
      ['Crase','Crase geralmente surge quando a preposição a encontra o artigo feminino a. O teste do masculino ajuda: “vou ao local” sugere “vou à escola”. Não use crase automaticamente só porque a palavra seguinte é feminina.','Prática: explique por que há ou não há crase em “entreguei o documento à diretora” e “comecei a estudar”.'],
      ['Pontuação e sentido','Vírgula não representa simplesmente uma pausa da fala. Ela organiza estruturas sintáticas e pode mudar relações de sentido. Não separe sujeito e verbo sem uma estrutura intercalada que justifique a pontuação.','Prática: reescreva três frases retirando vírgulas desnecessárias e explique a mudança.'],
      ['Reescrita e coesão','Em reescrita, a banca testa correção e preservação de sentido. Observe pronomes, conectivos, tempos verbais e relações de causa, oposição ou conclusão. Trocar “portanto” por “porém”, por exemplo, muda a lógica.','Prática: substitua um conectivo de conclusão por outro equivalente em um parágrafo curto.']
    ]},
    logica:{title:'Raciocínio Lógico',lessons:[
      ['Proposições','Proposição é uma sentença declarativa que pode ser verdadeira ou falsa. Perguntas, ordens e frases abertas com variável sem valor definido não são proposições no sentido clássico usado em provas.','Prática: classifique cinco frases do seu cotidiano em proposição ou não proposição.'],
      ['Conectivos','Na conjunção “p e q”, as duas precisam ser verdadeiras. Na disjunção “p ou q”, basta pelo menos uma. A condicional “se p, então q” só é falsa quando p é verdadeira e q é falsa.','Prática: construa uma tabela-verdade simples para p e q usando “e” e “ou”.'],
      ['Negação','Negar não é colocar “não” em qualquer lugar. A negação de “todos” vira “existe pelo menos um que não”; a de “existe” vira “nenhum”. Em conectivos, as leis de De Morgan ajudam a trocar e/ou corretamente.','Prática: negue a frase “Todos os candidatos estudam Português”.'],
      ['Porcentagem e razão','Porcentagem pode ser tratada como fator multiplicativo. Aumentar 20% é multiplicar por 1,20; reduzir 20%, por 0,80. Razão compara grandezas e proporção iguala duas razões.','Prática: calcule o preço após aumento de 15% de um item de R$ 200 sem usar regra de três.'],
      ['Sequências e padrões','Antes de procurar uma fórmula sofisticada, teste diferenças, multiplicações, alternância e agrupamentos. Muitas sequências de prova combinam dois padrões simples intercalados.','Prática: descubra os dois próximos termos de 2, 5, 4, 10, 6, 15... e explique o padrão.'],
      ['Problemas lógicos','Traduza o texto para relações menores. Identifique o que é dado, o que deve ser encontrado e quais restrições existem. Tabelas e desenhos simples evitam manter todas as condições na memória.','Prática: resolva um problema de ordem usando uma tabela antes de tentar mentalmente.']
    ]},
    matematica:{title:'Matemática Fundamental',lessons:[
      ['Operações e prioridade','Parênteses vêm antes de potências; multiplicação e divisão antes de adição e subtração. Quando operações têm a mesma prioridade, siga da esquerda para a direita.','Prática: resolva 8 + 2 × (5 − 1) e explique cada etapa.'],
      ['Frações e decimais','Frações representam partes de uma unidade ou razões. Para somar frações com denominadores diferentes, use um denominador comum. Decimais e porcentagens são outras formas de representar a mesma ideia.','Prática: transforme 3/4 em decimal e porcentagem.'],
      ['Regra de três com sentido','Antes de montar a conta, pergunte se as grandezas crescem juntas ou em sentidos opostos. A regra de três é uma forma organizada de trabalhar proporcionalidade, não uma fórmula automática.','Prática: se 4 cadernos custam R$ 28, calcule o preço de 7 mantendo o mesmo valor unitário.'],
      ['Equações','Resolver uma equação é encontrar o valor que torna a igualdade verdadeira. Faça a mesma operação nos dois lados para preservar o equilíbrio.','Prática: resolva 3x + 5 = 20 e depois substitua o resultado para verificar.'],
      ['Geometria básica','Perímetro mede o contorno; área mede a superfície. Retângulo: área = base × altura. Triângulo: base × altura ÷ 2. Desenhar e marcar unidades reduz erros.','Prática: calcule área e perímetro de um retângulo de 8 m por 5 m.'],
      ['Estatística básica','Média soma valores e divide pela quantidade; mediana é o valor central após ordenar; moda é o valor mais frequente. A escolha da medida depende dos dados.','Prática: calcule média, mediana e moda de 4, 5, 5, 6, 20.']
    ]},
    redacao:{title:'Redação',lessons:[
      ['Entender o tema','Antes de escrever, delimite exatamente o problema. Uma redação pode ser bem escrita e ainda fugir parcialmente do tema. Transforme o tema em uma pergunta e responda em uma frase.','Prática: escolha um tema atual e escreva uma resposta de uma frase que possa virar sua tese.'],
      ['Tese clara','A tese é a posição que organiza o texto. Ela não precisa ser uma frase pronta de modelo; precisa orientar os argumentos que virão. Evite introduções longas que não chegam ao problema.','Prática: escreva duas teses diferentes para o mesmo tema e compare qual é mais específica.'],
      ['Parágrafo argumentativo','Um bom parágrafo possui ideia central, desenvolvimento e relação com a tese. Exemplo ou repertório só ajuda quando é explicado; citar um autor sem conectar ao argumento não prova nada.','Prática: escreva um parágrafo com tópico frasal + explicação + exemplo.'],
      ['Coesão','Conectivos indicam relações: adição, oposição, causa, consequência e conclusão. Varie com naturalidade e evite usar palavras sofisticadas apenas para parecer formal.','Prática: reescreva um parágrafo usando dois conectivos sem repetir o mesmo.'],
      ['Conclusão','A conclusão fecha o raciocínio. No ENEM, a proposta de intervenção deve dialogar com o problema discutido e detalhar elementos suficientes para ser compreensível, respeitando direitos humanos.','Prática: crie uma conclusão que retome a tese sem copiar a introdução.'],
      ['Revisão final','Reserve tempo para procurar erros que prejudicam clareza: concordância, pontuação, repetição, palavras vagas e períodos longos demais. Revisar por camadas é melhor do que tentar observar tudo ao mesmo tempo.','Prática: revise um texto primeiro só para sentido, depois só para gramática e, por último, para repetição.']
    ]}
  };
  function state(){try{return JSON.parse(localStorage.getItem('rumo-lessons-v1')||'{}')}catch(_){return{}}}
  function saveState(x){localStorage.setItem('rumo-lessons-v1',JSON.stringify(x))}
  function progress(id){const c=courses[id];if(!c)return 0;const st=state()[id]?.done||[];return Math.round(st.length/c.lessons.length*100)}
  async function syncProgress(id){const r=R(),pct=progress(id);if(r.state.user)await r.sb.from('course_progress').upsert({user_id:r.state.user.id,course_id:id,progress:pct,updated_at:new Date().toISOString()},{onConflict:'user_id,course_id'});const card=r.qs(`[data-course="${id}"]`);if(card){let wrap=card.querySelector('.course-progress');if(!wrap){wrap=document.createElement('div');wrap.className='course-progress';wrap.innerHTML='<div class="line"><i></i></div><small></small>';card.appendChild(wrap)}wrap.querySelector('i').style.width=`${pct}%`;wrap.querySelector('small').textContent=`${pct}% concluído`}}
  function renderLesson(id,index){const r=R(),c=courses[id],lesson=c.lessons[index],host=r.qs('#course-modal-content');if(!c||!lesson||!host)return;const st=state(),done=new Set(st[id]?.done||[]);host.querySelectorAll('.lesson-btn').forEach((b,i)=>{b.classList.toggle('active',i===index);b.classList.toggle('done',done.has(i))});const content=host.querySelector('.lesson-content');content.innerHTML=`<div class="eyebrow">AULA ${index+1} DE ${c.lessons.length}</div><h3>${r.escapeHTML(lesson[0])}</h3><p class="lesson-lead">Leia com calma e faça a prática. A proposta dos Essenciais é terminar, não acumular horas de vídeo.</p><p>${r.escapeHTML(lesson[1])}</p><div class="lesson-box"><b>Faça agora</b><p>${r.escapeHTML(lesson[2])}</p></div><button class="primary lesson-complete" id="lesson-complete-v1">${done.has(index)?'✓ Aula concluída':'Concluir esta aula'}</button>`;r.qs('#lesson-complete-v1').onclick=async()=>{const data=state();data[id]=data[id]||{done:[]};const set=new Set(data[id].done||[]);set.add(index);data[id].done=[...set];saveState(data);await syncProgress(id);if(index<c.lessons.length-1)renderLesson(id,index+1);else{renderLesson(id,index);r.toast('Trilha concluída. Muito bom chegar até o fim.')}}
  function open(id){const r=R(),modal=r.qs('#course-modal'),host=r.qs('#course-modal-content');if(!modal||!host)return;const c=courses[id];if(!c){host.innerHTML=`<div class="eyebrow">ESSENCIAIS</div><h2>Trilha em preparação</h2><p>Este curso está no catálogo porque faz parte da direção do RUMO, mas ainda não vamos fingir que ele está pronto. Os primeiros cursos completos são Informática, Excel, Português, Raciocínio Lógico, Matemática e Redação.</p><div class="data-empty"><b>Em breve</b>Quando a trilha estiver no padrão de qualidade dos cursos principais, ela será liberada gratuitamente.</div>`;modal.classList.add('open');return}const st=state(),done=new Set(st[id]?.done||[]);host.innerHTML=`<div class="eyebrow">ESSENCIAIS · GRATUITO</div><h2>${r.escapeHTML(c.title)}</h2><p>${c.lessons.length} aulas curtas, prática imediata e progresso salvo.</p><div class="course-workspace"><aside class="lesson-nav"><h4>Trilha</h4>${c.lessons.map((l,i)=>`<button class="lesson-btn ${done.has(i)?'done':''}" data-lesson-index="${i}"><span class="lesson-number">${done.has(i)?'✓':i+1}</span><b>${r.escapeHTML(l[0])}</b></button>`).join('')}</aside><section class="lesson-content"></section></div>`;modal.classList.add('open');r.qsa('[data-lesson-index]',host).forEach(b=>b.onclick=()=>renderLesson(id,+b.dataset.lessonIndex));renderLesson(id,Math.min(c.lessons.length-1,done.size))}
  function decorate(){const r=R(),grid=r.qs('#course-grid');if(!grid)return;r.qsa('[data-course]',grid).forEach(card=>{const id=card.dataset.course,ready=!!courses[id];let badge=card.querySelector('.course-tag');if(badge){badge.textContent=ready?'GRÁTIS · PRONTO':'EM BREVE';if(!ready)badge.style.color='var(--muted)'}if(ready&&progress(id))syncProgress(id)})}
  document.addEventListener('click',e=>{const card=e.target.closest('[data-course]');if(card&&card.closest('#course-grid')){e.preventDefault();e.stopImmediatePropagation();open(card.dataset.course)}},true);const observer=new MutationObserver(()=>decorate());setTimeout(()=>{decorate();const g=R()?.qs('#course-grid');if(g)observer.observe(g,{childList:true,subtree:true})},1600);window.RUMO_COURSES={open,courses,progress};
})();