(() => {
  'use strict';
  const R=()=>window.RUMO;let pdfReady=null;
  const catalog=[
    ['Português',['língua portuguesa','português','lingua portuguesa']],['Raciocínio Lógico',['raciocínio lógico','raciocinio logico','lógica','logica']],['Matemática',['matemática','matematica']],['Informática',['informática','informatica','noções de informática','tecnologia da informação']],['Direito Constitucional',['direito constitucional']],['Direito Administrativo',['direito administrativo']],['Direito Tributário',['direito tributário','direito tributario']],['Direito Penal',['direito penal']],['Processo Penal',['processo penal','direito processual penal']],['Direito Civil',['direito civil']],['Processo Civil',['processo civil','direito processual civil']],['Contabilidade',['contabilidade geral','contabilidade pública','contabilidade publica','contabilidade']],['Auditoria',['auditoria']],['Administração Pública',['administração pública','administracao publica','administração geral']],['Gestão de Pessoas',['gestão de pessoas','gestao de pessoas']],['Arquivologia',['arquivologia']],['Redação Oficial',['redação oficial','redacao oficial']],['Ética no Serviço Público',['ética no serviço público','etica no servico publico','ética']],['Legislação',['legislação específica','legislacao especifica','legislação']],['SUS e Saúde Pública',['saúde pública','saude publica','sistema único de saúde','sistema unico de saude','sus']],['Conhecimentos Pedagógicos',['conhecimentos pedagógicos','conhecimentos pedagogicos','didática','didatica']],['Legislação Educacional',['legislação educacional','legislacao educacional','ldb']],['Conhecimentos Específicos',['conhecimentos específicos','conhecimentos especificos']]
  ];
  function loadPdf(){if(window.pdfjsLib)return Promise.resolve(window.pdfjsLib);if(pdfReady)return pdfReady;pdfReady=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.min.js';s.onload=()=>{window.pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js';resolve(window.pdfjsLib)};s.onerror=reject;document.head.appendChild(s)});return pdfReady}
  function clean(s=''){return s.replace(/\s+/g,' ').replace(/^[-–—•·\d.)\s]+/,'').trim()}
  function dedupe(arr){const seen=new Set();return arr.filter(x=>{const k=x.toLowerCase();if(seen.has(k))return false;seen.add(k);return true})}
  function detectSubjects(text,lines){const lower=text.toLowerCase(),found=[];for(const [name,aliases] of catalog){let idx=-1,alias='';for(const a of aliases){const i=lower.indexOf(a);if(i>=0&&(idx<0||i<idx)){idx=i;alias=a}}if(idx>=0)found.push({name,index:idx,alias})}found.sort((a,b)=>a.index-b.index);for(let i=0;i<found.length;i++){const cur=found[i],end=found[i+1]?.index??Math.min(text.length,cur.index+5000),chunk=text.slice(cur.index+cur.alias.length,end),pieces=chunk.split(/;|\n|\s+[a-z]\)\s+|\s+\d+[.)]\s+/i).map(clean).filter(x=>x.length>=5&&x.length<=150&&!/^(conhecimentos|conteúdo|conteudo|prova|cargo|edital)$/i.test(x));cur.topics=dedupe(pieces).slice(0,14)}if(found.length<2){const candidates=dedupe(lines.map(clean).filter(x=>x.length>4&&x.length<75&&x===x.toUpperCase()&&/[A-ZÁÉÍÓÚÇ]/.test(x)&&!/EDITAL|ANEXO|CARGO|PROVA|CRONOGRAMA|INSCRI|RESULTADO|TÍTULO|TITULO/.test(x))).slice(0,12);for(const c of candidates)if(!found.some(x=>x.name.toLowerCase()===c.toLowerCase()))found.push({name:c.replace(/\b\w/g,m=>m.toUpperCase()),topics:[]})}return found.slice(0,18)}
  async function extract(file){const lib=await loadPdf(),pdf=await lib.getDocument({data:await file.arrayBuffer()}).promise;let all=[],lines=[];for(let p=1;p<=pdf.numPages;p++){const page=await pdf.getPage(p),content=await page.getTextContent(),items=content.items||[];all.push(items.map(x=>x.str).join(' '));let current=[],lastY=null;for(const it of items){const y=Math.round(it.transform?.[5]||0);if(lastY!==null&&Math.abs(y-lastY)>3&&current.length){lines.push(current.join(' '));current=[]}current.push(it.str);lastY=y}if(current.length)lines.push(current.join(' '))}return {text:all.join('\n'),lines,pages:pdf.numPages}}
  async function merge(found,file){const r=R(),s=r.state;if(!s.user||!s.userConcurso)throw new Error('login');let newSubjects=0,newTopics=0;for(const f of found){let mat=s.materias.find(m=>m.nome.toLowerCase()===f.name.toLowerCase());if(!mat){const {data,error}=await r.sb.from('materias').insert({user_concurso_id:s.userConcurso.id,nome:f.name,peso:1.1,prioridade:'media'}).select().single();if(error)continue;mat=data;s.materias.push(mat);newSubjects++}const existing=s.topicos.filter(t=>t.materia_id===mat.id).map(t=>t.nome.toLowerCase());const rows=(f.topics||[]).filter(x=>!existing.includes(x.toLowerCase())).map(nome=>({materia_id:mat.id,nome}));if(rows.length){const {data}=await r.sb.from('topicos').insert(rows).select();s.topicos.push(...(data||[]));newTopics+=(data||[]).length}}await r.sb.from('edital_imports').insert({user_id:s.user.id,goal_id:s.goal?.id||null,file_name:file.name,subjects_found:found.length,topics_found:found.reduce((a,x)=>a+(x.topics?.length||0),0)});await r.refreshStructure();r.emit('plan-refresh',{});return {newSubjects,newTopics}}
  async function handle(file){const r=R(),status=r.qs('#edital-status-v1');if(!file)return;if(!r.state.user){r.toast('Entre na sua conta para salvar o conteúdo do edital.');return}if(status)status.textContent='Lendo o PDF no seu navegador...';try{const {text,lines,pages}=await extract(file);if(text.replace(/\s/g,'').length<200){if(status)status.textContent='Não encontrei texto suficiente. O PDF pode estar escaneado como imagem.';return}const found=detectSubjects(text,lines);if(!found.length){if(status)status.textContent='O PDF foi lido, mas não consegui identificar matérias com segurança. Tente um edital com o conteúdo programático em texto.';return}if(status)status.textContent=`Encontrei ${found.length} matérias em ${pages} páginas. Atualizando seu mapa...`;const result=await merge(found,file);if(status)status.textContent=`Pronto: ${found.length} matérias identificadas, ${result.newSubjects} novas e ${result.newTopics} tópicos adicionados. O plano foi recalculado.`;r.toast('Edital transformado em mapa de estudos')}catch(e){if(status)status.textContent='Não consegui processar este PDF. Tente outra versão do edital.'}}
  document.addEventListener('rumo:goal-page',()=>{const input=R().qs('#edital-file-v1');if(input&&!input.dataset.bound){input.dataset.bound='1';input.addEventListener('change',e=>handle(e.target.files?.[0]))}});window.RUMO_EDITAL={handle,detectSubjects};
})();