(() => {
  'use strict';
  if(!window.RUMO||!window.RUMO_SHELL)return;
  const {sb,state,escapeHTML}=window.RUMO,shell=window.RUMO_SHELL;
  const TRACK='enem',MATRIX_URL='https://www.gov.br/inep/pt-br/centrais-de-conteudo/acervo-linha-editorial/publicacoes-institucionais/avaliacoes-e-exames-da-educacao-basica/matrizes-de-referencia-enem';
  const fallbackAreas=[
    {id:'enem-linguagens',short_name:'Linguagens',name:'Linguagens, Códigos e suas Tecnologias',order_index:1},
    {id:'enem-humanas',short_name:'Humanas',name:'Ciências Humanas e suas Tecnologias',order_index:2},
    {id:'enem-natureza',short_name:'Natureza',name:'Ciências da Natureza e suas Tecnologias',order_index:3},
    {id:'enem-matematica',short_name:'Matemática',name:'Matemática e suas Tecnologias',order_index:4},
    {id:'enem-redacao',short_name:'Redação',name:'Redação',order_index:5}
  ];
  const data={areas:[...fallbackAreas],topics:[],essays:[],questionCount:0,stats:{attempts:0,correct:0}};
  const q=(s,r=document)=>r.querySelector(s),qa=(s,r=document)=>[...r.querySelectorAll(s)],pct=(a,b)=>b?Math.round(a/b*100):0;
  const glyph=(body)=>`<svg viewBox="0 0 20 20" aria-hidden="true">${body}</svg>`;
  const icons={
    enem:glyph('<circle cx="10" cy="10" r="6.5" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M10 3.5v13M3.5 10h13" stroke="currentColor" stroke-width="1.2"/>'),
    q:glyph('<path d="M4 4.5h12v9H9l-3.5 2.5v-2.5H4z" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M7.5 8h5M7.5 10.5h3" stroke="currentColor" stroke-width="1.3"/>'),
    r:glyph('<path d="M5 3.5h7l3 3v10H5z" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M8 9h4M8 12h4" stroke="currentColor" stroke-width="1.3"/>'),
    s:glyph('<path d="M6 3.5h8v13H6z" fill="none" stroke="currentColor" stroke-width="1.5"/><path d="M8 7h4M8 10h4M8 13h2" stroke="currentColor" stroke-width="1.3"/>')
  };
  function navButton(id,label,icon){const b=document.createElement('button');b.className='nav rumo-enem-nav';b.dataset.tab=id;b.innerHTML=`<span class="nav-icon rumo-nav-glyph">${icon}</span>${escapeHTML(label)}`;b.onclick=()=>shell.switchTab(id);return b}
  function setupNav(){const nav=q('.sidebar nav'),hoje=nav&&q('[data-tab="hoje"]',nav),conc=nav&&q('[data-tab="concursos"]',nav),rev=nav&&q('[data-tab="revisoes"]',nav);if(!nav||!hoje||!conc||!rev)return;nav.replaceChildren(hoje,navButton('enem','ENEM',icons.enem),navButton('questoes','Questões',icons.q),navButton('redacao','Redação',icons.r),navButton('simulados','Simulados',icons.s),conc,rev);const sub=q('.brand-copy span');if(sub)sub.textContent='ENEM & concursos';const pro=q('.pro-card');if(pro)pro.hidden=true;document.body.classList.add('rumo-enem-v1')}
  function addPage(id,html){if(q(`#${id}`))return;const s=document.createElement('section');s.id=id;s.className='page rumo-enem-page';s.innerHTML=html;const conc=q('#concursos');conc?.parentNode.insertBefore(s,conc)}
  function setupPages(){
    addPage('enem',`<div class="rumo-section-head"><div><div class="eyebrow">MATRIZ ENEM</div><h1>Estude pelo que a prova <em>realmente mede.</em></h1><p>Áreas, habilidades, prática e revisão ligadas à matriz de referência do Inep.</p></div><a class="rumo-source-link" href="${MATRIX_URL}" target="_blank" rel="noopener noreferrer">Matriz oficial do Inep ↗</a></div><div id="enem-overview"></div>`);
    addPage('questoes',`<div class="rumo-section-head"><div><div class="eyebrow">PRÁTICA</div><h1>Questões com <em>feedback imediato.</em></h1><p>Filtre por área e assunto. Cada resposta alimenta seu histórico.</p></div><div id="enem-question-stats" class="rumo-inline-stats"></div></div><div class="rumo-question-layout"><aside class="rumo-filter-panel"><label>Área<select id="enem-area-filter"></select></label><label>Assunto<select id="enem-topic-filter"><option value="">Todos</option></select></label><button class="primary" id="enem-new-list">Nova sequência</button><small>Base autoral RUMO alinhada ao ENEM.</small></aside><div id="enem-question-stage" class="rumo-question-stage"></div></div>`);
    addPage('redacao',`<div class="rumo-section-head"><div><div class="eyebrow">REDAÇÃO</div><h1>Treine uma competência <em>por vez.</em></h1><p>Escolha um tema, escreva e revise com as cinco competências.</p></div></div><div class="rumo-essay-layout"><aside id="enem-essay-list" class="rumo-essay-list"></aside><article class="rumo-editor"><div id="enem-essay-head"></div><textarea id="enem-essay-text" maxlength="30000" placeholder="Comece sua redação aqui..."></textarea><div class="rumo-editor-foot"><span id="enem-essay-count">0 palavras</span><span id="enem-essay-save">Rascunho local</span><button class="secondary" id="enem-save-draft">Salvar</button></div><div class="rumo-competencies">${['Norma-padrão','Compreensão do tema','Argumentação','Coesão','Proposta de intervenção'].map((x,i)=>`<label><input type="checkbox"><span><b>C${i+1}</b>${x}</span></label>`).join('')}</div></article></div>`);
    addPage('simulados',`<div class="rumo-section-head"><div><div class="eyebrow">SIMULADOS</div><h1>Treine pressão sem perder <em>diagnóstico.</em></h1><p>Monte um bloco rápido e veja o resultado apenas no final.</p></div></div><div id="enem-mock-root"></div>`)
  }
  function setupHome(){const hero=q('.hero-home');if(hero){const h=q('h1',hero),p=q('p',hero),b=q('#open-ai',hero);if(h)h.innerHTML='Seu próximo passo para o <em>ENEM.</em>';if(p)p.textContent='Estude o que importa, pratique questões, treine redação e use seus erros para definir a próxima revisão.';if(b){b.textContent='Resolver questões';b.onclick=()=>shell.switchTab('questoes')}}const strip=q('.objective-strip');if(strip&&!q('.rumo-enem-home')){const e=document.createElement('section');e.className='rumo-enem-home';e.innerHTML='<div class="rumo-home-copy"><small>FOCO PRINCIPAL</small><b>ENEM</b><span>Prática orientada pela matriz do Inep.</span></div><div class="rumo-home-metrics" id="enem-home-metrics"></div><div class="rumo-home-actions"><button class="secondary" data-go-enem="enem">Ver matriz</button><button class="primary" data-go-enem="questoes">Começar questões</button></div>';strip.insertAdjacentElement('afterend',e);qa('[data-go-enem]',e).forEach(b=>b.onclick=()=>shell.switchTab(b.dataset.goEnem))}}
  function renderStats(){const accuracy=pct(data.stats.correct,data.stats.attempts);const home=q('#enem-home-metrics');if(home)home.innerHTML=`<div><b>${data.questionCount}</b><span>questões ativas</span></div><div><b>${data.stats.attempts}</b><span>respondidas</span></div><div><b>${accuracy}%</b><span>acerto</span></div>`;const inline=q('#enem-question-stats');if(inline)inline.innerHTML=`<div><b>${data.stats.attempts}</b><span>respondidas</span></div><div><b>${accuracy}%</b><span>acerto</span></div>`}
  function renderOverview(){const root=q('#enem-overview');if(!root)return;const count=id=>data.topics.filter(t=>t.area_id===id).length;root.innerHTML=`<div class="rumo-axis"><small>EIXOS COGNITIVOS</small><div>${['Dominar linguagens','Compreender fenômenos','Enfrentar situações-problema','Construir argumentação','Elaborar propostas'].map((x,i)=>`<span><b>${i+1}</b>${x}</span>`).join('')}</div></div><div class="rumo-area-list">${data.areas.map(a=>`<button class="rumo-area-row" data-enem-area="${a.id}"><span class="rumo-area-index">${String(a.order_index||1).padStart(2,'0')}</span><span class="rumo-area-copy"><b>${escapeHTML(a.short_name||a.name)}</b><small>${escapeHTML(a.name)}</small></span><span class="rumo-area-meta">${count(a.id)} assuntos</span><span>→</span></button>`).join('')}</div><div class="rumo-enem-footnote"><b>Fonte estrutural</b><span>Matriz de Referência do ENEM — Inep, publicação de 2026.</span></div>`;qa('[data-enem-area]',root).forEach(b=>b.onclick=()=>{shell.switchTab('questoes');document.dispatchEvent(new CustomEvent('rumo:enem-area',{detail:{areaId:b.dataset.enemArea}}))})}
  async function loadCatalog(){try{const [a,t,e,c]=await Promise.all([sb.from('exam_areas').select('id,name,short_name,order_index').eq('track_id',TRACK).eq('active',true).order('order_index'),sb.from('exam_topics').select('id,area_id,name,description,order_index').eq('active',true).order('order_index'),sb.from('essay_topics').select('id,title,prompt,competencies').eq('track_id',TRACK).eq('active',true).order('created_at',{ascending:false}),sb.from('question_bank').select('id',{count:'exact',head:true}).eq('track_id',TRACK).eq('active',true).eq('verified',true)]);if(a.error)throw a.error;data.areas=a.data?.length?a.data:fallbackAreas;data.topics=t.data||[];data.essays=e.data||[];data.questionCount=c.count||0;document.documentElement.dataset.rumoEnem='ready'}catch(err){console.warn('RUMO ENEM catalog degraded',err);document.documentElement.dataset.rumoEnem='degraded'}renderOverview();renderStats();document.dispatchEvent(new CustomEvent('rumo:enem-ready',{detail:{data}}))}
  async function loadStats(){try{if(state.user){const r=await sb.from('question_attempts').select('correct').eq('user_id',state.user.id).order('created_at',{ascending:false}).limit(500);if(r.error)throw r.error;data.stats={attempts:r.data?.length||0,correct:(r.data||[]).filter(x=>x.correct).length}}else{const s=JSON.parse(localStorage.getItem('rumo-enem-guest-stats')||'{"attempts":0,"correct":0}');data.stats={attempts:Number(s.attempts)||0,correct:Number(s.correct)||0}}}catch(err){console.warn('RUMO ENEM stats degraded',err)}renderStats()}
  function bump(correct,n=1){data.stats.attempts+=n;if(correct===true)data.stats.correct++;renderStats()}
  setupNav();setupPages();setupHome();renderStats();document.addEventListener('rumo:context',loadStats);Promise.allSettled([loadCatalog(),loadStats()]);
  window.RUMO_ENEM={TRACK,data,q,qa,pct,bump,shell,escapeHTML,sb,state,loadCatalog,loadStats};
})();