(() => {
  'use strict';
  const get=()=>window.RUMO;
  const matBy=id=>get().state.materias.find(x=>x.id===id);
  const topBy=id=>get().state.topicos.find(x=>x.id===id);
  const isoDow=iso=>new Date(`${iso}T12:00:00`).getDay();
  function studyDates(start,count,allowed){const R=get(),out=[];let d=start,i=0;while(out.length<count&&i<40){if((allowed||[1,2,3,4,5]).includes(isoDow(d)))out.push(d);d=R.addDays(d,1);i++}return out}
  function topicScore(t,date){const R=get(),m=matBy(t.materia_id),q=(t.acertos||0)+(t.erros||0),err=q?(t.erros||0)/q:0;let s=(Number(m?.peso)||1)*100+err*55;if(t.status==='nao_iniciado')s+=18;if(t.proxima_revisao&&t.proxima_revisao.slice(0,10)<=date)s+=65;return s}
  function chooseTopic(date,used=new Set(),mode='estudo'){const R=get(),tops=R.state.topicos.filter(t=>!used.has(t.id));if(!tops.length)return null;let list=tops;if(mode==='revisao'){const due=tops.filter(t=>t.proxima_revisao&&t.proxima_revisao.slice(0,10)<=date);if(due.length)list=due}else if(mode==='questoes'){const practiced=tops.filter(t=>t.status!=='nao_iniciado'||(t.acertos+t.erros)>0);if(practiced.length)list=practiced}return [...list].sort((a,b)=>topicScore(b,date)-topicScore(a,date))[0]||null}
  function allocation(total){if(total<=60)return[['estudo',Math.round(total*.58)],['questoes',total-Math.round(total*.58)]];if(total<=120){const a=Math.round(total*.44),b=Math.round(total*.34);return[['estudo',a],['questoes',b],['revisao',total-a-b]]}const a=Math.round(total*.4),b=Math.round(total*.35);return[['estudo',a],['questoes',b],['revisao',total-a-b]]}

  async function ensurePlan(force=false){const R=get(),s=R.state;if(!s.user||!s.goal||!s.userConcurso||!s.materias.length)return;const start=R.today(),end=R.addDays(start,20);if(force)await R.sb.from('plano_tarefas').delete().eq('user_id',s.user.id).gte('data',start).eq('concluida',false);const {data:existing}=await R.sb.from('plano_tarefas').select('*').eq('user_id',s.user.id).gte('data',start).lte('data',end);const byDate=new Map((existing||[]).map(x=>[x.data,true]));const allowed=s.goal.study_days?.length?s.goal.study_days:[1,2,3,4,5],dates=studyDates(start,12,allowed);const daily=Math.max(30,Math.min(300,Math.round((Number(s.goal.weekly_hours)||10)*60/allowed.length)));const rows=[];for(const date of dates){if(byDate.has(date))continue;const used=new Set();for(const [type,raw] of allocation(daily)){const topic=chooseTopic(date,used,type);if(!topic)continue;used.add(topic.id);const mat=matBy(topic.materia_id);rows.push({user_id:s.user.id,user_concurso_id:s.userConcurso.id,materia_id:mat?.id||null,topico_id:topic.id,titulo:`${mat?.nome||'Estudo'} — ${topic.nome}`,tipo:type,data:date,minutos:Math.max(15,Math.round(raw/5)*5)})}}if(rows.length)await R.sb.from('plano_tarefas').insert(rows);await carryOver();await loadTasks();}

  async function carryOver(){const R=get(),s=R.state;if(!s.user)return;const today=R.today();const {data:old}=await R.sb.from('plano_tarefas').select('*').eq('user_id',s.user.id).lt('data',today).eq('concluida',false).order('data').limit(3);if(!old?.length)return;const {count}=await R.sb.from('plano_tarefas').select('id',{count:'exact',head:true}).eq('user_id',s.user.id).eq('data',today).eq('concluida',false);const free=Math.max(0,3-(count||0));for(const t of old.slice(0,free))await R.sb.from('plano_tarefas').update({data:today}).eq('id',t.id)}

  async function loadTasks(){const R=get(),s=R.state;if(!s.user){s.tasks=[];renderGuestPlan();return}const {data}=await R.sb.from('plano_tarefas').select('*').eq('user_id',s.user.id).eq('data',R.today()).order('criado_em');s.tasks=data||[];renderToday();R.emit('tasks',{tasks:s.tasks});}

  function renderGuestPlan(){const R=get(),box=R.qs('#study-list');if(!box)return;const goal=R.state.goal;if(!goal)return;const tpl=R.templates[R.templateKey(goal,null)].slice(0,3);const mins=Math.max(45,Math.round((Number(goal.weekly_hours)||8)*60/Math.max(1,(goal.study_days||[1,2,3,4,5]).length)));let left=mins;box.innerHTML=tpl.map((x,i)=>{const m=i===tpl.length-1?left:Math.max(15,Math.round(mins/[tpl.length]/5)*5);left-=m;return `<button class="study rumo-task" style="--task-accent:${i===0?'var(--accent)':i===1?'var(--cyan)':'var(--orange)'}"><div class="num">${i+1}</div><div class="task-copy"><b>${R.escapeHTML(x[0])}</b><span>${R.escapeHTML(x[2][0])}</span><span class="task-type">plano demonstrativo</span></div><div class="task-open"><div class="time">${m} min</div></div></button>`}).join('');const h=R.qs('.focus-card h2');if(h)h.textContent=`${R.formatMinutes(mins)} de estudo hoje`;const p=R.qs('.focus-card .progress');if(p)p.textContent='0%'}

  function typeLabel(t){return ({estudo:'Aprender',questoes:'Praticar',revisao:'Revisar'})[t]||'Estudar'}
  function taskColor(t){return ({estudo:'var(--accent)',questoes:'var(--green)',revisao:'var(--orange)'})[t]||'var(--accent)'}
  function renderToday(){const R=get(),s=R.state,box=R.qs('#study-list');if(!box)return;const tasks=s.tasks||[],done=tasks.filter(t=>t.concluida).length,total=tasks.reduce((a,t)=>a+t.minutos,0);box.innerHTML=tasks.length?tasks.map((t,i)=>{const m=matBy(t.materia_id),tp=topBy(t.topico_id);return `<button class="study rumo-task ${t.concluida?'done':''}" data-task-id="${t.id}" style="--task-accent:${taskColor(t.tipo)}"><div class="num">${t.concluida?'✓':i+1}</div><div class="task-copy"><b>${R.escapeHTML(m?.nome||t.titulo.split('—')[0].trim())}</b><span>${R.escapeHTML(tp?.nome||t.titulo.split('—').slice(1).join('—').trim())}</span><span class="task-type">${typeLabel(t.tipo)}</span></div><div class="task-open"><div class="time">${t.minutos} min</div><span class="task-arrow">›</span></div></button>`}).join(''):`<div class="data-empty"><b>Nada pendente agora.</b>O RUMO não encontrou tarefas para hoje. Ajuste sua rotina ou regenere o plano.</div>`;const h=R.qs('.focus-card h2');if(h)h.textContent=`${R.formatMinutes(total)} de estudo hoje`;const p=R.qs('.focus-card .progress');if(p)p.textContent=tasks.length?`${Math.round(done/tasks.length*100)}%`:'0%';R.qsa('[data-task-id]',box).forEach(b=>b.onclick=()=>{const t=tasks.find(x=>x.id===b.dataset.taskId);if(t)R.emit('open-session',{task:t})});ensureLogButton()}

  function ensureLogButton(){const R=get(),head=R.qs('.focus-card .card-heading');if(!head||R.qs('#log-study-v1'))return;const oldProgress=head.querySelector('.progress'),wrap=document.createElement('div');wrap.className='focus-actions-v1';if(oldProgress)wrap.appendChild(oldProgress);const btn=document.createElement('button');btn.id='log-study-v1';btn.className='log-study-v1';btn.textContent='+ Registrar estudo';wrap.appendChild(btn);head.appendChild(wrap);btn.onclick=()=>R.emit('open-manual-session',{})}

  async function renderAnalytics(){const R=get(),s=R.state;if(!s.user)return;const start=new Date();start.setDate(start.getDate()-6);start.setHours(0,0,0,0);const {data}=await R.sb.from('sessoes_estudo').select('*').eq('user_id',s.user.id).gte('estudado_em',start.toISOString()).order('estudado_em');const list=data||[],days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);days.push({key:d.toDateString(),min:0})}list.forEach(x=>{const d=days.find(y=>y.key===new Date(x.estudado_em).toDateString());if(d)d.min+=x.minutos});const max=Math.max(30,...days.map(x=>x.min));R.qsa('.activity-chart .bar-day').forEach((el,i)=>{el.querySelector('i')?.style.setProperty('--h',`${Math.max(8,Math.round(days[i].min/max*100))}%`);el.title=`${days[i].min} min`});const total=list.reduce((a,x)=>a+x.minutos,0),active=days.filter(x=>x.min>0).length,q=list.reduce((a,x)=>a+x.questoes,0),correct=list.reduce((a,x)=>a+x.acertos,0),accuracy=q?Math.round(correct/q*100):0;const mini=R.qsa('.activity-card .mini-stats>div');if(mini[0])mini[0].querySelector('b').textContent=R.formatMinutes(total);if(mini[1])mini[1].querySelector('b').textContent=active?R.formatMinutes(Math.round(total/active)):'0h';if(mini[2])mini[2].querySelector('b').textContent=active;const donut=R.qs('.performance-card .donut');if(donut){donut.style.background=`conic-gradient(var(--accent) 0 ${accuracy}%,var(--surface-3) ${accuracy}% 100%)`;const b=donut.querySelector('b');if(b)b.textContent=q?`${accuracy}%`:'—'}const metrics=R.qsa('.performance-card .metric b');if(metrics[0])metrics[0].textContent=q;if(metrics[1])metrics[1].textContent=list.length?`${list.length} sessões`:'Sem dados ainda';const goalMin=(Number(s.goal?.weekly_hours)||10)*60;const hours=R.qs('.week-card .hours');if(hours)hours.innerHTML=`${R.formatMinutes(total)} <span>/ ${Number(s.goal?.weekly_hours||10).toLocaleString('pt-BR')}h</span>`;const bar=R.qs('.week-card .goal-bar i');if(bar)bar.style.width=`${Math.min(100,Math.round(total/goalMin*100))}%`;const wk=R.qsa('.week-card .metric b');if(wk[0])wk[0].textContent=`${Math.min(100,Math.round(active/Math.max(1,s.goal?.study_days?.length||5)*100))}%`;if(wk[1]){const due=s.topicos.filter(t=>t.proxima_revisao&&t.proxima_revisao.slice(0,10)<=R.today()).length;wk[1].textContent=due?`${due} pendentes`:'100%'}}

  async function renderObjective(){const R=get(),s=R.state;if(!s.goal)return;const divs=R.qsa('.objective-strip>div');if(divs[0])divs[0].querySelector('b').textContent=s.goal.objective_name;const left=R.daysUntil(s.goal.prova_data);if(divs[1])divs[1].querySelector('b').textContent=left===null?'A definir':left===0?'É hoje!':left>0?`${left} dias`:'Realizada';let pct=0;if(s.user){const start=R.addDays(R.today(),-14);const {data}=await R.sb.from('plano_tarefas').select('concluida').eq('user_id',s.user.id).gte('data',start).lte('data',R.today());if(data?.length)pct=Math.round(data.filter(x=>x.concluida).length/data.length*100)}if(divs[2]){divs[2].querySelector('small').textContent='PLANO CONCLUÍDO';divs[2].querySelector('b').textContent=`${pct}%`}const hero=R.qs('.hero-home p');if(hero)hero.textContent=`Seu foco é ${s.goal.objective_name}. O plano se ajusta à sua rotina, ao que você conclui e ao que precisa revisar.`}

  async function renderGoalPage(){const R=get(),s=R.state,grid=R.qs('#meu .setup-grid');if(!grid||!s.goal)return;grid.className='goal-dashboard';let latest=null;if(s.user){const {data}=await R.sb.from('edital_imports').select('*').eq('user_id',s.user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();latest=data||null}const left=R.daysUntil(s.goal.prova_data),planType=latest?`Edital importado · ${latest.subjects_found} matérias`:'Plano-base RUMO';grid.innerHTML=`<article class="goal-main-card"><div class="eyebrow">OBJETIVO ATUAL</div><h2>${R.escapeHTML(s.goal.objective_name)}</h2><p>${s.goal.cargo?R.escapeHTML(s.goal.cargo):'Preparação personalizada'} · ${R.escapeHTML(planType)}</p><div class="goal-kpis-v1"><div><b>${left===null?'—':Math.max(0,left)}</b><span>dias até a prova</span></div><div><b>${Number(s.goal.weekly_hours||10).toLocaleString('pt-BR')}h</b><span>por semana</span></div><div><b>${(s.goal.study_days||[]).length}</b><span>dias de estudo</span></div></div><button class="secondary" id="goal-adjust-v1" style="margin-top:16px">Ajustar objetivo e rotina</button></article><article class="goal-side-card"><div class="eyebrow">EDITAL INTELIGENTE</div><h3>Transforme o PDF em plano.</h3><p>O arquivo é lido no seu navegador. O RUMO procura matérias e tópicos e atualiza sua trilha sem enviar o PDF para nosso servidor.</p><label class="edital-drop"><input id="edital-file-v1" type="file" accept="application/pdf"><b>Selecionar edital em PDF</b><span>Funciona melhor com PDFs que permitem selecionar texto.</span></label><div class="edital-status" id="edital-status-v1">${latest?`Último: ${R.escapeHTML(latest.file_name)} · ${new Date(latest.created_at).toLocaleDateString('pt-BR')}`:'Nenhum edital importado ainda.'}</div><button class="secondary" id="regenerate-plan-v1" style="width:100%;margin-top:12px">Recalcular próximos dias</button></article><article class="subjects-card"><div class="eyebrow">MAPA DO CONTEÚDO</div><h3>Matérias e domínio</h3><div class="subjects-list">${s.materias.length?s.materias.map(m=>{const tops=s.topicos.filter(t=>t.materia_id===m.id),done=tops.filter(t=>t.status==='dominado').length,pct=tops.length?Math.round(done/tops.length*100):m.progresso||0;return `<div class="subject-row"><div><b>${R.escapeHTML(m.nome)}</b><small>${tops.length} tópicos</small></div><div class="subject-bar"><i style="width:${pct}%"></i></div><b>${pct}%</b><span class="priority-pill ${m.prioridade}">${m.prioridade}</span></div>`}).join(''):'<div class="data-empty"><b>Conteúdo ainda não estruturado.</b>Personalize seu objetivo ou importe o edital.</div>'}</div></article>`;R.qs('#goal-adjust-v1')?.addEventListener('click',()=>R.qs('#personalize-btn')?.click());R.qs('#regenerate-plan-v1')?.addEventListener('click',async()=>{R.toast('Recalculando seu plano...');await ensurePlan(true);R.toast('Plano atualizado')});R.emit('goal-page',{latest})}

  async function boot(){const R=get();if(!R?.state.ready)return;await ensurePlan();await Promise.all([renderAnalytics(),renderObjective(),renderGoalPage()])}
  document.addEventListener('rumo:context',()=>setTimeout(boot,80));document.addEventListener('rumo:structure',()=>setTimeout(renderGoalPage,60));document.addEventListener('rumo:session-saved',()=>setTimeout(async()=>{await RUMO.refreshStructure();await loadTasks();await renderAnalytics();await renderObjective();await renderGoalPage()},80));document.addEventListener('rumo:plan-refresh',()=>ensurePlan(true));setTimeout(()=>{if(get()?.state.ready)boot()},1700);
  window.RUMO_ENGINE={ensurePlan,loadTasks,renderAnalytics,renderGoalPage};
})();