(() => {
  'use strict';
  const R=()=>window.RUMO;
  let installPrompt=null;
  const pad=n=>String(n).padStart(2,'0');
  const escICS=s=>String(s||'').replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\n/g,'\\n');
  const localDateTime=(date,time)=>new Date(`${date}T${time}:00`);
  const icsStamp=d=>`${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}Z`;
  const googleStamp=d=>icsStamp(d);
  function taskLabel(t){const r=R(),m=r.state.materias.find(x=>x.id===t.materia_id),tp=r.state.topicos.find(x=>x.id===t.topico_id);return `${m?.nome||'Estudo'} — ${tp?.nome||t.titulo||'Sessão RUMO'}`}
  function taskDescription(tasks){return tasks.map((t,i)=>`${i+1}. ${taskLabel(t)} (${t.minutos} min)`).join('\n')}
  async function weekTasks(){const r=R(),s=r.state;if(!s.user)return (s.tasks||[]).map(t=>({...t,data:r.today()}));const end=r.addDays(r.today(),6);const {data,error}=await r.sb.from('plano_tarefas').select('*').eq('user_id',s.user.id).gte('data',r.today()).lte('data',end).order('data').order('criado_em');if(error)throw error;return data||[]}
  function defaultTime(){const d=new Date();d.setMinutes(Math.ceil(d.getMinutes()/30)*30,0,0);if(d.getHours()>=22)return'19:00';return`${pad(d.getHours())}:${pad(d.getMinutes())}`}
  function googleToday(tasks,time){const r=R(),today=tasks.filter(t=>(t.data||r.today())===r.today()&&!t.concluida);if(!today.length){r.toast('Não há tarefas pendentes hoje.');return}const start=localDateTime(r.today(),time),minutes=today.reduce((a,t)=>a+(Number(t.minutos)||0),0),end=new Date(start.getTime()+Math.max(20,minutes)*60000),params=new URLSearchParams({action:'TEMPLATE',text:`RUMO · ${r.state.goal?.objective_name||'Estudo de hoje'}`,dates:`${googleStamp(start)}/${googleStamp(end)}`,details:`Plano de hoje no RUMO:\n\n${taskDescription(today)}\n\nAbra o RUMO para registrar a sessão.`,ctz:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo'});window.open(`https://calendar.google.com/calendar/render?${params.toString()}`,'_blank','noopener,noreferrer')}
  async function downloadICS(tasks,time,gap){const r=R();if(!tasks.length){r.toast('Seu plano ainda não tem tarefas para exportar.');return}const groups=Object.groupBy?Object.groupBy(tasks,t=>t.data||r.today()):tasks.reduce((a,t)=>{const k=t.data||r.today();(a[k]||(a[k]=[])).push(t);return a},{}),events=[];for(const [date,list] of Object.entries(groups)){let cursor=localDateTime(date,time);for(const t of list.filter(x=>!x.concluida)){const start=new Date(cursor),end=new Date(start.getTime()+Math.max(10,Number(t.minutos)||30)*60000);events.push(['BEGIN:VEVENT',`UID:${crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)}@eden-rumo`,`DTSTAMP:${icsStamp(new Date())}`,`DTSTART:${icsStamp(start)}`,`DTEND:${icsStamp(end)}`,`SUMMARY:${escICS(`RUMO · ${taskLabel(t)}`)}`,`DESCRIPTION:${escICS(`Sessão planejada pelo EDEN RUMO. Tipo: ${t.tipo||'estudo'}.`)}`,'END:VEVENT'].join('\r\n'));cursor=new Date(end.getTime()+gap*60000)}}const body=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//EDEN//RUMO//PT-BR','CALSCALE:GREGORIAN','METHOD:PUBLISH',...events,'END:VCALENDAR'].join('\r\n');const blob=new Blob([body],{type:'text/calendar;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rumo-plano-${r.today()}.ics`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);r.toast(`${events.length} sessões exportadas para calendário.`)}
  async function notify(){if(!('Notification'in window)){R().toast('Seu navegador não oferece notificações.');return}const perm=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(perm!=='granted'){R().toast('Permissão de notificação não concedida.');return}const reg=await navigator.serviceWorker?.ready.catch(()=>null);if(reg)await reg.showNotification('RUMO pronto para estudar',{body:'Notificações estão funcionando neste dispositivo.',icon:'./favicon.svg',badge:'./favicon.svg',tag:'rumo-test'});else new Notification('RUMO pronto para estudar',{body:'Notificações estão funcionando neste dispositivo.'});R().toast('Notificação de teste enviada.')}
  async function install(){const r=R();if(installPrompt){installPrompt.prompt();const choice=await installPrompt.userChoice;if(choice.outcome==='accepted')r.toast('RUMO instalado.');installPrompt=null;paintInstall();return}r.toast('No navegador, use “Instalar aplicativo” ou “Adicionar à tela inicial”.')}
  async function share(){const data={title:'EDEN RUMO',text:'RUMO — planejamento inteligente para estudos e concursos.',url:location.origin};if(navigator.share){try{await navigator.share(data)}catch(_){}}else{await navigator.clipboard?.writeText(location.origin);R().toast('Link do RUMO copiado.')}}
  function paintInstall(){const b=R()?.qs('#rumo-install-v1');if(b)b.textContent=installPrompt?'Instalar RUMO':'Como instalar'}
  function inject(){const r=R();if(r.qs('#integrations-v1'))return;document.body.insertAdjacentHTML('beforeend',`<div id="integrations-v1" class="modal"><div class="modal-card integrations-shell"><button class="close" id="integrations-close-v1">×</button><div class="eyebrow">INTEGRAÇÕES</div><h2>Conecte o RUMO à sua rotina.</h2><p class="integrations-lead">Agenda, instalação e recursos do dispositivo sem entregar seus dados a serviços desnecessários.</p><div class="integration-grid"><section class="integration-card live"><div class="integration-head"><span>CALENDÁRIO</span><b>Ativo</b></div><h3>Google Agenda e outros calendários</h3><p>Adicione o estudo de hoje ao Google Agenda ou exporte a semana em .ics para Google, Outlook e Apple Calendar.</p><div class="integration-fields"><label>Início do estudo<input id="calendar-time-v1" type="time" value="${defaultTime()}"></label><label>Intervalo entre sessões<input id="calendar-gap-v1" type="number" min="0" max="60" value="10"><span>min</span></label></div><div class="integration-actions"><button class="primary" id="google-today-v1">Adicionar hoje ao Google Agenda</button><button class="secondary" id="ics-week-v1">Exportar semana (.ics)</button></div></section><section class="integration-card live"><div class="integration-head"><span>DISPOSITIVO</span><b>Ativo</b></div><h3>RUMO como aplicativo</h3><p>Instale o RUMO, compartilhe o endereço e confira se as notificações do navegador estão liberadas.</p><div class="integration-actions"><button class="secondary" id="rumo-install-v1">Como instalar</button><button class="secondary" id="rumo-notify-v1">Testar notificação</button><button class="secondary" id="rumo-share-v1">Compartilhar RUMO</button></div></section><section class="integration-card status"><div class="integration-head"><span>SERVIÇOS</span><b>Produção</b></div><div class="integration-status-list"><div><i class="ok"></i><span>Supabase · conta e dados</span><b>Conectado</b></div><div><i class="ok"></i><span>Vercel · hospedagem</span><b>Conectado</b></div><div><i class="ok"></i><span>AI Gateway · Assistente</span><b>Automático</b></div><div><i class="pending"></i><span>Pagamentos</span><b>Falta provedor</b></div><div><i class="pending"></i><span>E-mail transacional</span><b>Falta SMTP</b></div></div></section></div></div></div>`);r.qs('#integrations-close-v1').onclick=()=>r.qs('#integrations-v1').classList.remove('open');r.qs('#integrations-v1').onclick=e=>{if(e.target.id==='integrations-v1')e.currentTarget.classList.remove('open')};r.qs('#google-today-v1').onclick=async()=>googleToday(await weekTasks(),r.qs('#calendar-time-v1').value||'19:00');r.qs('#ics-week-v1').onclick=async()=>downloadICS(await weekTasks(),r.qs('#calendar-time-v1').value||'19:00',Math.max(0,+r.qs('#calendar-gap-v1').value||0));r.qs('#rumo-notify-v1').onclick=notify;r.qs('#rumo-install-v1').onclick=install;r.qs('#rumo-share-v1').onclick=share;paintInstall()}
  function accountButton(){const r=R(),actions=r.qs('#account-v3 .account-actions');if(!actions||r.qs('#account-integrations-v1'))return;const b=document.createElement('button');b.id='account-integrations-v1';b.textContent='◫ Integrações e agenda';b.onclick=()=>{inject();r.qs('#account-v3')?.classList.remove('open');r.qs('#integrations-v1').classList.add('open')};actions.insertBefore(b,r.qs('#account-logout-v3'))}
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;paintInstall()});window.addEventListener('appinstalled',()=>{installPrompt=null;paintInstall()});
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js',{scope:'./'}).catch(err=>console.warn('RUMO service worker unavailable',err));
  inject();accountButton();document.addEventListener('rumo:context',accountButton);document.addEventListener('click',e=>{if(e.target.closest?.('#account-btn'))setTimeout(accountButton,0)},true);window.RUMO_INTEGRATIONS={open:()=>{inject();R().qs('#integrations-v1').classList.add('open')},weekTasks};
})();