(() => {
  'use strict';
  const R=()=>window.RUMO;
  let config=null,busy=false;
  function b64ToUint8(base64){const pad='='.repeat((4-base64.length%4)%4),b64=(base64+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b64),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
  async function getConfig(){if(config)return config;try{const r=await fetch('/api/push-config',{cache:'no-store'});config=await r.json();return config}catch(_){return config={enabled:false,publicKey:null}}}
  async function currentSubscription(){if(!('serviceWorker'in navigator))return null;const reg=await navigator.serviceWorker.ready.catch(()=>null);return reg?reg.pushManager.getSubscription():null}
  async function saveSubscription(sub){const r=R(),u=r.state.user;if(!u)return false;const data=sub.toJSON(),keys=data.keys||{};const {error}=await r.sb.from('push_subscriptions').upsert({user_id:u.id,endpoint:data.endpoint,p256dh:keys.p256dh||null,auth_secret:keys.auth||null,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'America/Sao_Paulo',enabled:true,updated_at:new Date().toISOString()},{onConflict:'user_id,endpoint'});if(error)return false;await r.sb.from('user_preferences').upsert({user_id:u.id,reminder_enabled:true,updated_at:new Date().toISOString()},{onConflict:'user_id'});return true}
  async function enable(){const r=R();if(busy)return false;if(!r.state.user){r.toast('Entre na sua conta para ativar lembretes.');return false}busy=true;try{const cfg=await getConfig();if(!cfg.enabled||!cfg.publicKey){r.toast('Push em segundo plano ainda não está configurado. A notificação local continua disponível.');return false}if(!('Notification'in window)||!('serviceWorker'in navigator)){r.toast('Seu navegador não oferece push em segundo plano.');return false}const permission=Notification.permission==='granted'?'granted':await Notification.requestPermission();if(permission!=='granted'){r.toast('Permissão de notificação não concedida.');return false}const reg=await navigator.serviceWorker.ready;let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8(cfg.publicKey)});if(!await saveSubscription(sub)){r.toast('Não consegui salvar o dispositivo agora.');return false}r.toast('Lembretes do RUMO ativados neste dispositivo.');window.RUMO_ANALYTICS?.track('integration_opened',{feature:'push_enabled'});paint();return true}catch(error){console.warn('RUMO push enable',error);r.toast('Não consegui ativar push neste dispositivo.');return false}finally{busy=false}}
  async function disable(){const r=R();if(!r.state.user)return;busy=true;try{const sub=await currentSubscription();if(sub){await r.sb.from('push_subscriptions').update({enabled:false,updated_at:new Date().toISOString()}).eq('user_id',r.state.user.id).eq('endpoint',sub.endpoint);await sub.unsubscribe().catch(()=>{})}await r.sb.from('user_preferences').upsert({user_id:r.state.user.id,reminder_enabled:false,updated_at:new Date().toISOString()},{onConflict:'user_id'});r.toast('Lembretes em segundo plano desativados.');paint()}finally{busy=false}}
  async function status(){const r=R(),cfg=await getConfig(),sub=await currentSubscription();return{available:!!cfg.enabled,supported:'Notification'in window&&'serviceWorker'in navigator,subscribed:!!sub,permission:'Notification'in window?Notification.permission:'unsupported',loggedIn:!!r.state.user}}
  async function paint(){const r=R(),btn=r.qs('#rumo-push-v1'),label=r.qs('#rumo-push-status-v1');if(!btn||!label)return;const s=await status();if(!s.available){btn.textContent='Push aguardando configuração';btn.disabled=true;label.textContent='Notificação local disponível; push com o site fechado será ativado quando as chaves VAPID entrarem.';return}btn.disabled=busy||!s.loggedIn;btn.textContent=s.subscribed?'Desativar lembretes':'Ativar lembretes';btn.dataset.mode=s.subscribed?'disable':'enable';label.textContent=s.subscribed?'Este dispositivo receberá lembretes mesmo com o RUMO fechado.':'Ative para receber lembretes do plano neste dispositivo.'}
  function injectIntoIntegrations(){const r=R(),grid=r.qs('#integrations-v1 .integration-grid');if(!grid||r.qs('#push-card-v1'))return;const card=document.createElement('section');card.className='integration-card live';card.id='push-card-v1';card.innerHTML='<div class="integration-head"><span>LEMBRETES</span><b>Push</b></div><h3>Estudo mesmo com o RUMO fechado</h3><p id="rumo-push-status-v1">Verificando disponibilidade...</p><div class="integration-actions"><button class="secondary" id="rumo-push-v1">Verificando...</button></div>';grid.insertBefore(card,grid.lastElementChild);r.qs('#rumo-push-v1').onclick=async e=>{if(e.currentTarget.dataset.mode==='disable')await disable();else await enable()};paint()}
  document.addEventListener('rumo:context',()=>setTimeout(()=>{injectIntoIntegrations();paint()},50));document.addEventListener('click',e=>{if(e.target.closest?.('#account-integrations-v1'))setTimeout(()=>{injectIntoIntegrations();paint()},0)},true);setTimeout(()=>{injectIntoIntegrations();paint()},2400);window.RUMO_PUSH={enable,disable,status,paint};
})();
